/*
 * COPYRIGHT STATUS: © 2015, 2016.  This work, authored by Cognitive Medical Systems
 * employees, was funded in whole or in part by The Department of Veterans
 * Affairs under U.S. Government contract VA118-11-D-1011 / VA118-1011-0013.
 * The copyright holder agrees to post or allow the Government to post all or
 * part of this work in open-source repositories subject to the Apache License,
 * Version 2.0, dated January 2004. All other rights are reserved by the
 * copyright owner.
 *
 * For use outside the Government, the following notice applies:
 *
 *     Copyright 2015 © Cognitive Medical Systems
 *
 *     Licensed under the Apache License, Version 2.0 (the "License"); you may
 *     not use this file except in compliance with the License. You may obtain
 *     a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */
package Bounce_v1_6_1

import org.opencds.vmr.v1_0.internal.EvaluatedPerson;
import org.opencds.vmr.v1_0.internal.EvaluatedPersonAgeAtEvalTime
import org.opencds.vmr.v1_0.internal.ClinicalStatement
import org.opencds.vmr.v1_0.internal.Demographics;
import org.opencds.vmr.v1_0.internal.FocalPersonId;
import org.opencds.vmr.v1_0.internal.datatypes.IVLDate;
import org.opencds.vmr.v1_0.internal.datatypes.CD;
import org.opencds.vmr.v1_0.internal.FocalPersonId;
import org.opencds.vmr.v1_0.internal.ObservationResult
import org.opencds.vmr.v1_0.internal.ObservationValue
import org.opencds.vmr.v1_0.internal.EncounterEvent
import org.opencds.vmr.v1_0.internal.concepts.VmrOpenCdsConcept
import org.joda.time.Period;
import org.joda.time.PeriodType;
import java.util.Date;
import java.text.DecimalFormat;

import java.util.ArrayList;
import java.util.List;

global java.lang.String clientLanguage
global java.lang.String clientTimeZoneOffset
global java.lang.String focalPersonId
global java.util.Date evalTime
global java.util.HashSet assertions
global java.util.HashMap namedObjects
 

 
 
rule "agent-orange-exposure"
			dialect "java", no-loop true
			when
				$person : EvaluatedPerson()
				$ee:EncounterEvent($type:encounterType)
				
				eval($type.getOriginalText().equals("agent-orange"))	
				eval($type.getDisplayName().equals("Yes"))	
			then	
			java.util.Date now = new java.util.Date();
			IVLDate testDate = new IVLDate();
			testDate.setLow(now);
			testDate.setHigh(now);
	
			ObservationResult observationResult = new ObservationResult();
			observationResult.setObservationEventTime(testDate);
	 		String observationProposalId = "2.16.840.1.113883.3.1829.11.1.2.1";
	 		observationResult.setId(observationProposalId);
	 		observationResult.setEvaluatedPersonId($person.getId());
	 		observationResult.setSubjectIsFocalPerson(true);
			observationResult.setClinicalStatementToBeRoot(true);
			observationResult.setToBeReturned(true);
			
			DecimalFormat twoPlaces = new DecimalFormat("#.##");
			//Setup the ObservationFocus
			CD focus = new CD();
			focus.setCode("427272008");
			focus.setCodeSystem("snomed");
			focus.setCodeSystemName("snomed");
			focus.setDisplayName("VA's Advice for Agent Orange Exposure Risk");
			focus.setOriginalText("http://www.publichealth.va.gov/exposures/agentorange/conditions/");
			observationResult.setObservationFocus(focus);
			//Setup the ObservationValue
			ObservationValue value = new ObservationValue();
			value.setText("US10400, US9720: Please note that this patient has been exposed to Agent Orange, and may be eligible for benefits for related conditions. For a list of presumptive diseases associated with this exposure, please see: http://www.publichealth.va.gov/exposures/agentorange/conditions/"); 
			observationResult.setObservationValue(value);
			
			insert(observationResult);
			System.out.println("***************** Inserting ObservationResult\n");
			
			namedObjects.put("observationResult", observationResult);
							
end 
