
package gov.va.med.jmeadows_2_3_3_0_2.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "JMeadowsDataService", targetNamespace = "http://webservice.jmeadows.med.va.gov/", wsdlLocation = "wsdl/jmeadows_2_3_3_0_2/JMeadowsDataService.wsdl")
public class JMeadowsDataService
    extends Service
{

    private final static URL JMEADOWSDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException JMEADOWSDATASERVICE_EXCEPTION;
    private final static QName JMEADOWSDATASERVICE_QNAME = new QName("http://webservice.jmeadows.med.va.gov/", "JMeadowsDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        url = JMeadowsDataService.class.getClassLoader().getResource("wsdl/jmeadows_2_3_3_0_2/JMeadowsDataService.wsdl");
        JMEADOWSDATASERVICE_WSDL_LOCATION = url;
        JMEADOWSDATASERVICE_EXCEPTION = e;
    }

    public JMeadowsDataService() {
        super(__getWsdlLocation(), JMEADOWSDATASERVICE_QNAME);
    }

    public JMeadowsDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JMEADOWSDATASERVICE_QNAME, features);
    }

    public JMeadowsDataService(URL wsdlLocation) {
        super(wsdlLocation, JMEADOWSDATASERVICE_QNAME);
    }

    public JMeadowsDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JMEADOWSDATASERVICE_QNAME, features);
    }

    public JMeadowsDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JMeadowsDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns JMeadowsData
     */
    @WebEndpoint(name = "JMeadowsDataPort")
    public JMeadowsData getJMeadowsDataPort() {
        return super.getPort(new QName("http://webservice.jmeadows.med.va.gov/", "JMeadowsDataPort"), JMeadowsData.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JMeadowsData
     */
    @WebEndpoint(name = "JMeadowsDataPort")
    public JMeadowsData getJMeadowsDataPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.jmeadows.med.va.gov/", "JMeadowsDataPort"), JMeadowsData.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JMEADOWSDATASERVICE_EXCEPTION!= null) {
            throw JMEADOWSDATASERVICE_EXCEPTION;
        }
        return JMEADOWSDATASERVICE_WSDL_LOCATION;
    }

}
