
package gov.va.med.jmeadows_2_3_3_0_2.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JMeadowsData", targetNamespace = "http://webservice.jmeadows.DNS       /")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JMeadowsData {


    /**
     * 
     * @param siteCode
     * @param verifyCode
     * @param accessCode
     * @param requestingApp
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.User
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.LoginResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/loginRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/loginResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/login/Fault/JMeadowsException")
    })
    public User login(
        @WebParam(name = "siteCode", targetNamespace = "")
        String siteCode,
        @WebParam(name = "accessCode", targetNamespace = "")
        String accessCode,
        @WebParam(name = "verifyCode", targetNamespace = "")
        String verifyCode,
        @WebParam(name = "requestingApp", targetNamespace = "")
        String requestingApp)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "auditSensitiveRecordAccess", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.AuditSensitiveRecordAccess")
    @ResponseWrapper(localName = "auditSensitiveRecordAccessResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.AuditSensitiveRecordAccessResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/auditSensitiveRecordAccessRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/auditSensitiveRecordAccessResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/auditSensitiveRecordAccess/Fault/JMeadowsException")
    })
    public void auditSensitiveRecordAccess(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.PatientAdmission>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientAdmissions", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientAdmissions")
    @ResponseWrapper(localName = "getPatientAdmissionsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientAdmissionsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientAdmissionsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientAdmissionsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientAdmissions/Fault/JMeadowsException")
    })
    public List<PatientAdmission> getPatientAdmissions(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "auditVARestrictedAccess", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.AuditVARestrictedAccess")
    @ResponseWrapper(localName = "auditVARestrictedAccessResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.AuditVARestrictedAccessResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/auditVARestrictedAccessRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/auditVARestrictedAccessResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/auditVARestrictedAccess/Fault/JMeadowsException")
    })
    public void auditVARestrictedAccess(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.ResponsePatientSelect
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPatientMVI", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SelectPatientMVI")
    @ResponseWrapper(localName = "selectPatientMVIResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SelectPatientMVIResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/selectPatientMVIRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/selectPatientMVIResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/selectPatientMVI/Fault/JMeadowsException")
    })
    public ResponsePatientSelect selectPatientMVI(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "selectPatientForVASensitive", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SelectPatientForVASensitive")
    @ResponseWrapper(localName = "selectPatientForVASensitiveResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SelectPatientForVASensitiveResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/selectPatientForVASensitiveRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/selectPatientForVASensitiveResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/selectPatientForVASensitive/Fault/JMeadowsException")
    })
    public void selectPatientForVASensitive(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param authUserInfoQuery
     * @return
     *     returns boolean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserSubjectDN", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.UpdateUserSubjectDN")
    @ResponseWrapper(localName = "updateUserSubjectDNResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.UpdateUserSubjectDNResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/updateUserSubjectDNRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/updateUserSubjectDNResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/updateUserSubjectDN/Fault/JMeadowsException")
    })
    public boolean updateUserSubjectDN(
        @WebParam(name = "authUserInfoQuery", targetNamespace = "")
        AuthUserInfo authUserInfoQuery)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param emailAddress
     * @param siteCode
     * @param verifyCode
     * @param cardID
     * @param accessCode
     * @param ipAddress
     * @param requestingApp
     * @param subjectDN
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.User
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginEnterprise", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.LoginEnterprise")
    @ResponseWrapper(localName = "loginEnterpriseResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.LoginEnterpriseResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/loginEnterpriseRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/loginEnterpriseResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/loginEnterprise/Fault/JMeadowsException")
    })
    public User loginEnterprise(
        @WebParam(name = "cardID", targetNamespace = "")
        String cardID,
        @WebParam(name = "siteCode", targetNamespace = "")
        String siteCode,
        @WebParam(name = "accessCode", targetNamespace = "")
        String accessCode,
        @WebParam(name = "verifyCode", targetNamespace = "")
        String verifyCode,
        @WebParam(name = "requestingApp", targetNamespace = "")
        String requestingApp,
        @WebParam(name = "ipAddress", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "subjectDN", targetNamespace = "")
        String subjectDN,
        @WebParam(name = "emailAddress", targetNamespace = "")
        String emailAddress)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Patient>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lookupPatient", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.LookupPatient")
    @ResponseWrapper(localName = "lookupPatientResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.LookupPatientResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/lookupPatientRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/lookupPatientResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/lookupPatient/Fault/JMeadowsException")
    })
    public List<Patient> lookupPatient(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.ResponsePatientQuery
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lookupPatientPDWS", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.LookupPatientPDWS")
    @ResponseWrapper(localName = "lookupPatientPDWSResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.LookupPatientPDWSResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/lookupPatientPDWSRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/lookupPatientPDWSResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/lookupPatientPDWS/Fault/JMeadowsException")
    })
    public ResponsePatientQuery lookupPatientPDWS(
        @WebParam(name = "queryBean", targetNamespace = "")
        PdwsQueryBean queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.Patient
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPatient", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SelectPatient")
    @ResponseWrapper(localName = "selectPatientResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SelectPatientResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/selectPatientRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/selectPatientResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/selectPatient/Fault/JMeadowsException")
    })
    public Patient selectPatient(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.AllergyDetail
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllergyDetail", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAllergyDetail")
    @ResponseWrapper(localName = "getAllergyDetailResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAllergyDetailResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getAllergyDetailRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getAllergyDetailResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getAllergyDetail/Fault/JMeadowsException")
    })
    public AllergyDetail getAllergyDetail(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.PatientHistory>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientHistory", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientHistory")
    @ResponseWrapper(localName = "getPatientHistoryResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientHistoryResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientHistoryRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientHistoryResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientHistory/Fault/JMeadowsException")
    })
    public List<PatientHistory> getPatientHistory(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Allergy>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientAllergies", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientAllergies")
    @ResponseWrapper(localName = "getPatientAllergiesResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientAllergiesResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientAllergiesRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientAllergiesResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientAllergies/Fault/JMeadowsException")
    })
    public List<Allergy> getPatientAllergies(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Allergy>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDODVLERPatientAllergies", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetDODVLERPatientAllergies")
    @ResponseWrapper(localName = "getDODVLERPatientAllergiesResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetDODVLERPatientAllergiesResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getDODVLERPatientAllergiesRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getDODVLERPatientAllergiesResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getDODVLERPatientAllergies/Fault/JMeadowsException")
    })
    public List<Allergy> getDODVLERPatientAllergies(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientEncountersReport", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientEncountersReport")
    @ResponseWrapper(localName = "getPatientEncountersReportResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientEncountersReportResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientEncountersReportRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientEncountersReportResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientEncountersReport/Fault/JMeadowsException")
    })
    public FreeTextReport getPatientEncountersReport(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.PatientAppointments>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientAppointments", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientAppointments")
    @ResponseWrapper(localName = "getPatientAppointmentsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientAppointmentsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientAppointmentsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientAppointmentsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientAppointments/Fault/JMeadowsException")
    })
    public List<PatientAppointments> getPatientAppointments(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Encounter>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientEncounters", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientEncounters")
    @ResponseWrapper(localName = "getPatientEncountersResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientEncountersResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientEncountersRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientEncountersResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientEncounters/Fault/JMeadowsException")
    })
    public List<Encounter> getPatientEncounters(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.ClinicalReminder>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientClinicalReminders", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientClinicalReminders")
    @ResponseWrapper(localName = "getPatientClinicalRemindersResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientClinicalRemindersResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientClinicalRemindersRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientClinicalRemindersResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientClinicalReminders/Fault/JMeadowsException")
    })
    public List<ClinicalReminder> getPatientClinicalReminders(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClinicalReminderDetail", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetClinicalReminderDetail")
    @ResponseWrapper(localName = "getClinicalReminderDetailResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetClinicalReminderDetailResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getClinicalReminderDetailRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getClinicalReminderDetailResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getClinicalReminderDetail/Fault/JMeadowsException")
    })
    public FreeTextReport getClinicalReminderDetail(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.PatientDemographics>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientDemographics", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientDemographics")
    @ResponseWrapper(localName = "getPatientDemographicsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientDemographicsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientDemographicsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientDemographicsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientDemographics/Fault/JMeadowsException")
    })
    public List<PatientDemographics> getPatientDemographics(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.PatientDemographicsDetail>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientDemographicsDetail", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientDemographicsDetail")
    @ResponseWrapper(localName = "getPatientDemographicsDetailResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientDemographicsDetailResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientDemographicsDetailRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientDemographicsDetailResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientDemographicsDetail/Fault/JMeadowsException")
    })
    public List<PatientDemographicsDetail> getPatientDemographicsDetail(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Immunization>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientImmunizations", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientImmunizations")
    @ResponseWrapper(localName = "getPatientImmunizationsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientImmunizationsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientImmunizationsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientImmunizationsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientImmunizations/Fault/JMeadowsException")
    })
    public List<Immunization> getPatientImmunizations(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.LabOrder>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientLabs", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientLabs")
    @ResponseWrapper(localName = "getPatientLabsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientLabsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabs/Fault/JMeadowsException")
    })
    public List<LabOrder> getPatientLabs(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.LabResult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientLabResults", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientLabResults")
    @ResponseWrapper(localName = "getPatientLabResultsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientLabResultsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabResultsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabResultsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabResults/Fault/JMeadowsException")
    })
    public List<LabResult> getPatientLabResults(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientLabReport", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientLabReport")
    @ResponseWrapper(localName = "getPatientLabReportResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientLabReportResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabReportRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabReportResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabReport/Fault/JMeadowsException")
    })
    public FreeTextReport getPatientLabReport(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Medication>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientMedications", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientMedications")
    @ResponseWrapper(localName = "getPatientMedicationsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientMedicationsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientMedicationsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientMedicationsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientMedications/Fault/JMeadowsException")
    })
    public List<Medication> getPatientMedications(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Form>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientForms", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientForms")
    @ResponseWrapper(localName = "getPatientFormsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientFormsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientFormsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientFormsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientForms/Fault/JMeadowsException")
    })
    public List<Form> getPatientForms(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.ProgressNote>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientProgressNotes", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientProgressNotes")
    @ResponseWrapper(localName = "getPatientProgressNotesResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientProgressNotesResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientProgressNotesRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientProgressNotesResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientProgressNotes/Fault/JMeadowsException")
    })
    public List<ProgressNote> getPatientProgressNotes(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.NoteImage
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBHIENoteImage", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetBHIENoteImage")
    @ResponseWrapper(localName = "getBHIENoteImageResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetBHIENoteImageResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getBHIENoteImageRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getBHIENoteImageResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getBHIENoteImage/Fault/JMeadowsException")
    })
    public NoteImage getBHIENoteImage(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.ProgressNote>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientDischargeSummaries", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientDischargeSummaries")
    @ResponseWrapper(localName = "getPatientDischargeSummariesResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientDischargeSummariesResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientDischargeSummariesRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientDischargeSummariesResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientDischargeSummaries/Fault/JMeadowsException")
    })
    public List<ProgressNote> getPatientDischargeSummaries(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Consult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientConsultRequests", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientConsultRequests")
    @ResponseWrapper(localName = "getPatientConsultRequestsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientConsultRequestsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientConsultRequestsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientConsultRequestsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientConsultRequests/Fault/JMeadowsException")
    })
    public List<Consult> getPatientConsultRequests(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Order>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientOrders", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientOrders")
    @ResponseWrapper(localName = "getPatientOrdersResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientOrdersResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientOrdersRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientOrdersResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientOrders/Fault/JMeadowsException")
    })
    public List<Order> getPatientOrders(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Problem>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientProblemList", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientProblemList")
    @ResponseWrapper(localName = "getPatientProblemListResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientProblemListResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientProblemListRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientProblemListResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientProblemList/Fault/JMeadowsException")
    })
    public List<Problem> getPatientProblemList(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.RadiologyReport>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientRads", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientRads")
    @ResponseWrapper(localName = "getPatientRadsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientRadsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientRadsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientRadsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientRads/Fault/JMeadowsException")
    })
    public List<RadiologyReport> getPatientRads(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Vitals>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientVitals", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientVitals")
    @ResponseWrapper(localName = "getPatientVitalsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientVitalsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientVitalsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientVitalsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientVitals/Fault/JMeadowsException")
    })
    public List<Vitals> getPatientVitals(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.LabResult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientLabTestResults", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientLabTestResults")
    @ResponseWrapper(localName = "getPatientLabTestResultsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientLabTestResultsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabTestResultsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabTestResultsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientLabTestResults/Fault/JMeadowsException")
    })
    public List<LabResult> getPatientLabTestResults(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.LabResult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLabOrderResult", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetLabOrderResult")
    @ResponseWrapper(localName = "getLabOrderResultResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetLabOrderResultResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getLabOrderResultRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getLabOrderResultResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getLabOrderResult/Fault/JMeadowsException")
    })
    public List<LabResult> getLabOrderResult(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.AdmissionDetail
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdmissionDetails", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAdmissionDetails")
    @ResponseWrapper(localName = "getAdmissionDetailsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAdmissionDetailsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getAdmissionDetailsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getAdmissionDetailsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getAdmissionDetails/Fault/JMeadowsException")
    })
    public AdmissionDetail getAdmissionDetails(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Diagnosis>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdmissionDiagnosis", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAdmissionDiagnosis")
    @ResponseWrapper(localName = "getAdmissionDiagnosisResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAdmissionDiagnosisResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getAdmissionDiagnosisRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getAdmissionDiagnosisResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getAdmissionDiagnosis/Fault/JMeadowsException")
    })
    public List<Diagnosis> getAdmissionDiagnosis(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Procedure>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdmissionProcedures", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAdmissionProcedures")
    @ResponseWrapper(localName = "getAdmissionProceduresResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAdmissionProceduresResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getAdmissionProceduresRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getAdmissionProceduresResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getAdmissionProcedures/Fault/JMeadowsException")
    })
    public List<Procedure> getAdmissionProcedures(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.FreeTextReport>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConsultReport", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetConsultReport")
    @ResponseWrapper(localName = "getConsultReportResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetConsultReportResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getConsultReportRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getConsultReportResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getConsultReport/Fault/JMeadowsException")
    })
    public List<FreeTextReport> getConsultReport(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.User
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderProfile", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderProfile")
    @ResponseWrapper(localName = "getProviderProfileResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderProfileResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderProfileRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderProfileResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderProfile/Fault/JMeadowsException")
    })
    public User getProviderProfile(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMedicationDetail", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetMedicationDetail")
    @ResponseWrapper(localName = "getMedicationDetailResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetMedicationDetailResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getMedicationDetailRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getMedicationDetailResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getMedicationDetail/Fault/JMeadowsException")
    })
    public FreeTextReport getMedicationDetail(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderDetail", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetOrderDetail")
    @ResponseWrapper(localName = "getOrderDetailResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetOrderDetailResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getOrderDetailRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getOrderDetailResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getOrderDetail/Fault/JMeadowsException")
    })
    public FreeTextReport getOrderDetail(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Vitals>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientCurrentVitals", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientCurrentVitals")
    @ResponseWrapper(localName = "getPatientCurrentVitalsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientCurrentVitalsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientCurrentVitalsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientCurrentVitalsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientCurrentVitals/Fault/JMeadowsException")
    })
    public List<Vitals> getPatientCurrentVitals(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.InsuranceBean>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientInsurances", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientInsurances")
    @ResponseWrapper(localName = "getPatientInsurancesResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetPatientInsurancesResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientInsurancesRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientInsurancesResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getPatientInsurances/Fault/JMeadowsException")
    })
    public List<InsuranceBean> getPatientInsurances(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Procedure>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOutpatientProcedures", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetOutpatientProcedures")
    @ResponseWrapper(localName = "getOutpatientProceduresResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetOutpatientProceduresResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getOutpatientProceduresRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getOutpatientProceduresResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getOutpatientProcedures/Fault/JMeadowsException")
    })
    public List<Procedure> getOutpatientProcedures(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.ProblemDetail
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProblemDetail", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProblemDetail")
    @ResponseWrapper(localName = "getProblemDetailResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProblemDetailResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProblemDetailRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProblemDetailResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProblemDetail/Fault/JMeadowsException")
    })
    public ProblemDetail getProblemDetail(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProgressNote", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProgressNote")
    @ResponseWrapper(localName = "getProgressNoteResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProgressNoteResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProgressNoteRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProgressNoteResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProgressNote/Fault/JMeadowsException")
    })
    public FreeTextReport getProgressNote(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.RadiologyReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRadiologyReport", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetRadiologyReport")
    @ResponseWrapper(localName = "getRadiologyReportResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetRadiologyReportResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getRadiologyReportRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getRadiologyReportResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getRadiologyReport/Fault/JMeadowsException")
    })
    public RadiologyReport getRadiologyReport(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.VlerDocument>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVLERDocumentList", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetVLERDocumentList")
    @ResponseWrapper(localName = "getVLERDocumentListResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetVLERDocumentListResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getVLERDocumentListRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getVLERDocumentListResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getVLERDocumentList/Fault/JMeadowsException")
    })
    public List<VlerDocument> getVLERDocumentList(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param vDoc
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.VlerDocument
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVLERDocument", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetVLERDocument")
    @ResponseWrapper(localName = "getVLERDocumentResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetVLERDocumentResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getVLERDocumentRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getVLERDocumentResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getVLERDocument/Fault/JMeadowsException")
    })
    public VlerDocument getVLERDocument(
        @WebParam(name = "vDoc", targetNamespace = "")
        VlerDocument vDoc,
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Vlerccda>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDODVLERPatientCCDA", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetDODVLERPatientCCDA")
    @ResponseWrapper(localName = "getDODVLERPatientCCDAResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetDODVLERPatientCCDAResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getDODVLERPatientCCDARequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getDODVLERPatientCCDAResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getDODVLERPatientCCDA/Fault/JMeadowsException")
    })
    public List<Vlerccda> getDODVLERPatientCCDA(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Alert>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserAlerts", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetUserAlerts")
    @ResponseWrapper(localName = "getUserAlertsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetUserAlertsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getUserAlertsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getUserAlertsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getUserAlerts/Fault/JMeadowsException")
    })
    public List<Alert> getUserAlerts(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVisitNotes", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetVisitNotes")
    @ResponseWrapper(localName = "getVisitNotesResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetVisitNotesResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getVisitNotesRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getVisitNotesResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getVisitNotes/Fault/JMeadowsException")
    })
    public FreeTextReport getVisitNotes(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param siteCode
     * @param endDate
     * @param userNPI
     * @param patId
     * @param userName
     * @param providerIen
     * @param emailAddress
     * @param cardId
     * @param requestingApp
     * @param category
     * @param userIen
     * @param startDate
     * @param info
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "logAudit", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.LogAudit")
    @ResponseWrapper(localName = "logAuditResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.LogAuditResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/logAuditRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/logAuditResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/logAudit/Fault/JMeadowsException")
    })
    public void logAudit(
        @WebParam(name = "siteCode", targetNamespace = "")
        String siteCode,
        @WebParam(name = "userIen", targetNamespace = "")
        String userIen,
        @WebParam(name = "providerIen", targetNamespace = "")
        String providerIen,
        @WebParam(name = "userNPI", targetNamespace = "")
        String userNPI,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "patId", targetNamespace = "")
        String patId,
        @WebParam(name = "category", targetNamespace = "")
        String category,
        @WebParam(name = "requestingApp", targetNamespace = "")
        String requestingApp,
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate,
        @WebParam(name = "info", targetNamespace = "")
        String info,
        @WebParam(name = "cardId", targetNamespace = "")
        String cardId,
        @WebParam(name = "emailAddress", targetNamespace = "")
        String emailAddress)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.PatientAppointments>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderAppointments", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderAppointments")
    @ResponseWrapper(localName = "getProviderAppointmentsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderAppointmentsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderAppointmentsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderAppointmentsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderAppointments/Fault/JMeadowsException")
    })
    public List<PatientAppointments> getProviderAppointments(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.PatientAdmission>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderAdmissions", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderAdmissions")
    @ResponseWrapper(localName = "getProviderAdmissionsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderAdmissionsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderAdmissionsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderAdmissionsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderAdmissions/Fault/JMeadowsException")
    })
    public List<PatientAdmission> getProviderAdmissions(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.PatientAdmission>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWardAdmissions", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetWardAdmissions")
    @ResponseWrapper(localName = "getWardAdmissionsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetWardAdmissionsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getWardAdmissionsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getWardAdmissionsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getWardAdmissions/Fault/JMeadowsException")
    })
    public List<PatientAdmission> getWardAdmissions(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.ProgressNote>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderUnsignedNotes", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderUnsignedNotes")
    @ResponseWrapper(localName = "getProviderUnsignedNotesResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderUnsignedNotesResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderUnsignedNotesRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderUnsignedNotesResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderUnsignedNotes/Fault/JMeadowsException")
    })
    public List<ProgressNote> getProviderUnsignedNotes(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Consult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderConsultsRequested", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderConsultsRequested")
    @ResponseWrapper(localName = "getProviderConsultsRequestedResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderConsultsRequestedResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderConsultsRequestedRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderConsultsRequestedResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderConsultsRequested/Fault/JMeadowsException")
    })
    public List<Consult> getProviderConsultsRequested(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Consult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderConsultsReceived", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderConsultsReceived")
    @ResponseWrapper(localName = "getProviderConsultsReceivedResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderConsultsReceivedResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderConsultsReceivedRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderConsultsReceivedResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderConsultsReceived/Fault/JMeadowsException")
    })
    public List<Consult> getProviderConsultsReceived(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Order>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderOrdersPending", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderOrdersPending")
    @ResponseWrapper(localName = "getProviderOrdersPendingResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderOrdersPendingResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderOrdersPendingRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderOrdersPendingResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderOrdersPending/Fault/JMeadowsException")
    })
    public List<Order> getProviderOrdersPending(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Order>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderOrdersResulted", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderOrdersResulted")
    @ResponseWrapper(localName = "getProviderOrdersResultedResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderOrdersResultedResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderOrdersResultedRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderOrdersResultedResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderOrdersResulted/Fault/JMeadowsException")
    })
    public List<Order> getProviderOrdersResulted(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.LabResult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderLabAbnormalResults", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderLabAbnormalResults")
    @ResponseWrapper(localName = "getProviderLabAbnormalResultsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderLabAbnormalResultsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderLabAbnormalResultsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderLabAbnormalResultsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderLabAbnormalResults/Fault/JMeadowsException")
    })
    public List<LabResult> getProviderLabAbnormalResults(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.lang.String
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJanusGUIConfig", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetJanusGUIConfig")
    @ResponseWrapper(localName = "getJanusGUIConfigResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetJanusGUIConfigResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getJanusGUIConfigRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getJanusGUIConfigResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getJanusGUIConfig/Fault/JMeadowsException")
    })
    public String getJanusGUIConfig(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param cfg
     * @param queryBean
     * @return
     *     returns boolean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setJanusGUIConfig", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SetJanusGUIConfig")
    @ResponseWrapper(localName = "setJanusGUIConfigResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SetJanusGUIConfigResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/setJanusGUIConfigRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/setJanusGUIConfigResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/setJanusGUIConfig/Fault/JMeadowsException")
    })
    public boolean setJanusGUIConfig(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean,
        @WebParam(name = "cfg", targetNamespace = "")
        String cfg)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.lang.String
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderFlags", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderFlags")
    @ResponseWrapper(localName = "getProviderFlagsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetProviderFlagsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderFlagsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderFlagsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getProviderFlags/Fault/JMeadowsException")
    })
    public String getProviderFlags(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param flags
     * @param queryBean
     * @return
     *     returns boolean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setProviderFlags", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SetProviderFlags")
    @ResponseWrapper(localName = "setProviderFlagsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SetProviderFlagsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/setProviderFlagsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/setProviderFlagsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/setProviderFlags/Fault/JMeadowsException")
    })
    public boolean setProviderFlags(
        @WebParam(name = "queryBean", targetNamespace = "")
        JMeadowsQuery queryBean,
        @WebParam(name = "flags", targetNamespace = "")
        String flags)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param emailAddress
     * @param smartCardID
     * @param smartCardAgency
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.IehrUserProfile
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIehrUserProfile", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetIehrUserProfile")
    @ResponseWrapper(localName = "getIehrUserProfileResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetIehrUserProfileResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getIehrUserProfileRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getIehrUserProfileResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getIehrUserProfile/Fault/JMeadowsException")
    })
    public IehrUserProfile getIehrUserProfile(
        @WebParam(name = "smartCardID", targetNamespace = "")
        String smartCardID,
        @WebParam(name = "smartCardAgency", targetNamespace = "")
        String smartCardAgency,
        @WebParam(name = "emailAddress", targetNamespace = "")
        String emailAddress)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param iehrUserProfile
     * @return
     *     returns boolean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setIehrUserProfile", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SetIehrUserProfile")
    @ResponseWrapper(localName = "setIehrUserProfileResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.SetIehrUserProfileResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/setIehrUserProfileRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/setIehrUserProfileResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/setIehrUserProfile/Fault/JMeadowsException")
    })
    public boolean setIehrUserProfile(
        @WebParam(name = "iehrUserProfile", targetNamespace = "")
        IehrUserProfile iehrUserProfile)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Site>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSites", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetSites")
    @ResponseWrapper(localName = "getSitesResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetSitesResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getSitesRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getSitesResponse")
    public List<Site> getSites();

    /**
     * 
     * @param emailAddress
     * @param cardID
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.AuditEntry>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoginInfo", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetLoginInfo")
    @ResponseWrapper(localName = "getLoginInfoResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetLoginInfoResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getLoginInfoRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getLoginInfoResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getLoginInfo/Fault/JMeadowsException")
    })
    public List<AuditEntry> getLoginInfo(
        @WebParam(name = "cardID", targetNamespace = "")
        String cardID,
        @WebParam(name = "emailAddress", targetNamespace = "")
        String emailAddress)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceErrors", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetServiceErrors")
    @ResponseWrapper(localName = "getServiceErrorsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetServiceErrorsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getServiceErrorsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getServiceErrorsResponse")
    public String getServiceErrors();

    /**
     * 
     * @param authUserInfoQuery
     * @return
     *     returns gov.va.med.jmeadows_2_3_3_0_2.webservice.AuthUserInfo
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthUser", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAuthUser")
    @ResponseWrapper(localName = "getAuthUserResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetAuthUserResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getAuthUserRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getAuthUserResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getAuthUser/Fault/JMeadowsException")
    })
    public AuthUserInfo getAuthUser(
        @WebParam(name = "authUserInfoQuery", targetNamespace = "")
        AuthUserInfo authUserInfoQuery)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "resetStatus", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.ResetStatus")
    @ResponseWrapper(localName = "resetStatusResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.ResetStatusResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/resetStatusRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/resetStatusResponse")
    public void resetStatus();

    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_3_0_2.webservice.Patient>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecentlyViewedPatients", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetRecentlyViewedPatients")
    @ResponseWrapper(localName = "getRecentlyViewedPatientsResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetRecentlyViewedPatientsResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getRecentlyViewedPatientsRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getRecentlyViewedPatientsResponse", fault = {
        @FaultAction(className = JMeadowsException_Exception.class, value = "http://webservice.jmeadows.DNS       /JMeadowsData/getRecentlyViewedPatients/Fault/JMeadowsException")
    })
    public List<Patient> getRecentlyViewedPatients(
        @WebParam(name = "userId", targetNamespace = "")
        String userId)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetStatusResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getStatusRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getStatusResponse")
    public String getStatus();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://webservice.jmeadows.DNS       /", className = "gov.va.med.jmeadows_2_3_3_0_2.webservice.GetVersionResponse")
    @Action(input = "http://webservice.jmeadows.DNS       /JMeadowsData/getVersionRequest", output = "http://webservice.jmeadows.DNS       /JMeadowsData/getVersionResponse")
    public String getVersion();

}
