define([
    'main/ui_components/form/controls/alertBanner',
    'main/ui_components/form/controls/boolean',
    'main/ui_components/form/controls/button',
    'main/ui_components/form/controls/checklist',
    'main/ui_components/form/controls/collapsibleContainer',
    'main/ui_components/form/controls/commentBox',
    'main/ui_components/form/controls/container',
    'main/ui_components/form/controls/datepicker',
    'main/ui_components/form/controls/drilldownChecklist',
    'main/ui_components/form/controls/dropdown',
    'main/ui_components/form/controls/fieldset',
    'main/ui_components/form/controls/input',
    'main/ui_components/form/controls/multiselectSideBySide',
    'main/ui_components/form/controls/nestedCommentBox',
    'main/ui_components/form/controls/popover',
    'main/ui_components/form/controls/radio',
    'main/ui_components/form/controls/radioList',
    'main/ui_components/form/controls/rangeSlider',
    'main/ui_components/form/controls/searchbar',
    'main/ui_components/form/controls/select',
    'main/ui_components/form/controls/selectableTable',
    'main/ui_components/form/controls/selectList',
    'main/ui_components/form/controls/spacer',
    'main/ui_components/form/controls/tabs',
    'main/ui_components/form/controls/textarea',
    'main/ui_components/form/controls/timepicker',
    'main/ui_components/form/controls/toggleOptionsChecklist',
    'main/ui_components/form/controls/treepicker',
    'main/ui_components/form/controls/typeahead',
    'main/ui_components/form/controls/yesNoChecklist'
], function(
    AlertBanner,
    BooleanItem,
    Button,
    Checklist,
    CollapsibleContainer,
    CommentBox,
    Container,
    Datepicker,
    DrilldownChecklist,
    Dropdown,
    Fieldset,
    Input,
    MultiselectSideBySide,
    NestedCommentBox,
    Popover,
    Radio,
    RadioList,
    RangeSlider,
    Searchbar,
    Select,
    SelectableTable,
    SelectList,
    Spacer,
    Tabs,
    Textarea,
    Timepicker,
    ToggleOptionsChecklist,
    Treepicker,
    Typeahead,
    YesNoChecklist
) {
    "use strict";

    var FormControls = {
        AlertBannerControl: AlertBanner,
        BooleanControl: BooleanItem,
        ButtonControl: Button,
        CheckboxControl: BooleanItem,
        ChecklistControl: Checklist,
        CollapsibleContainerControl: CollapsibleContainer,
        CommentBoxControl: CommentBox,
        ContainerControl: Container,
        DatepickerControl: Datepicker,
        DrilldownChecklistControl: DrilldownChecklist,
        DropdownControl: Dropdown,
        FieldsetControl: Fieldset,
        InputControl: Input,
        MultiselectSideBySideControl: MultiselectSideBySide,
        NestedCommentBoxControl: NestedCommentBox,
        PopoverControl: Popover,
        RadioControl: Radio,
        RadioListControl: RadioList,
        RangeSliderControl: RangeSlider,
        SearchbarControl: Searchbar,
        SelectControl: Select,
        SelectableTableControl: SelectableTable,
        SelectListControl: SelectList,
        SpacerControl: Spacer,
        TabsControl: Tabs,
        TextareaControl: Textarea,
        TimepickerControl: Timepicker,
        ToggleOptionsChecklistControl: ToggleOptionsChecklist,
        TreepickerControl: Treepicker,
        TypeaheadControl: Typeahead,
        YesNoChecklistControl: YesNoChecklist
    };

    return FormControls;
});