package genderAge;

import org.joda.time.Period;
import org.joda.time.PeriodType;
import java.util.Date;
import java.text.DecimalFormat;

import ca.uhn.fhir.model.api.IDatatype;
import ca.uhn.fhir.model.dstu2.composite.CodeableConceptDt;
import ca.uhn.fhir.model.dstu2.composite.CodingDt;
import ca.uhn.fhir.model.dstu2.composite.ContainedDt;
import ca.uhn.fhir.model.dstu2.resource.CommunicationRequest;
import ca.uhn.fhir.model.dstu2.resource.CommunicationRequest.Payload;
import ca.uhn.fhir.model.dstu2.resource.Provenance;
import ca.uhn.fhir.model.dstu2.resource.Provenance.Agent;
import ca.uhn.fhir.model.dstu2.resource.Patient;
import ca.uhn.fhir.model.primitive.StringDt;
import java.util.ArrayList;
import java.util.ArrayList;
import java.util.List;
import java.lang.String;

import function org.opencds.service.evaluate.FhirUtils.isCodingContains;
import function org.opencds.service.evaluate.FhirUtils.getValueQuantity;
import function org.opencds.service.evaluate.FhirUtils.createProvenance;
import function org.opencds.service.evaluate.FhirUtils.createCommunicationRequest;
import function org.opencds.service.evaluate.FhirUtils.hasInputFlag;
import function org.opencds.service.evaluate.FhirUtils.createOutputExtension;

global java.lang.String clientLanguage;
global java.lang.String clientTimeZoneOffset;
global java.lang.String focalPersonId;
global java.util.Date evalTime;
global java.util.HashSet assertions;
global java.util.HashMap namedObjects;
 
rule "ageGenderFhirMale"
			dialect "java"
			when
				$patient : Patient($birthtime : birthDate, $gender : gender)
				$age : Period() from new Period($birthtime.getTime(), new Date().getTime(), PeriodType.years())
				
				eval($age.getYears() >= 45 )
				eval($gender.equals("male"))	
				
			then
			  CommunicationRequest comRequest = createCommunicationRequest("The risk of heart disease increases for men after age 45.");
		  
		      CodeableConceptDt category = new CodeableConceptDt("SNOMED", "419772000");
		      comRequest.setCategory(category);
		      category.getCodingFirstRep().setDisplay("Family Medicine");
		      category.setText("Family Medicine");
		      
		      CodeableConceptDt reason = new CodeableConceptDt("SNOMED", "419772000");
		      comRequest.getReason().add(reason);
		      reason.getCodingFirstRep().setDisplay("NIH Coronary Heart Disease Risk Reminder");
		      
		      CodeableConceptDt priority = new CodeableConceptDt("CDS-System", "50");
		      priority.getCodingFirstRep().setDisplay("Routine");
		      comRequest.setPriority(priority);
		      
		      Provenance prov = createProvenance("http://www.nhlbi.nih.gov/health/health-topics/topics/hd");
		      ContainedDt contained = new ContainedDt();
			  contained.getContainedResources().add(prov);
		      comRequest.setContained(contained);
		      comRequest.addUndeclaredExtension(createOutputExtension());
		      prov.addUndeclaredExtension(createOutputExtension());
		      namedObjects.put("provenance", prov);	
		      namedObjects.put("communicationRequest", comRequest);			
end 

rule "ageGenderFhirFemale"
			dialect "java"
			when
				$patient : Patient($birthtime : birthDate, $gender : gender)
				$age : Period() from new Period($birthtime.getTime(), new Date().getTime(), PeriodType.years())
				
				eval($age.getYears() >= 55 )
				eval($gender.equals("female"))	
			then
			  CommunicationRequest comRequest = createCommunicationRequest("The risk of heart disease increases for female after age 55.");
		  
		      CodeableConceptDt category = new CodeableConceptDt("SNOMED", "419772000");
		      comRequest.setCategory(category);
		      category.getCodingFirstRep().setDisplay("Family Medicine");
		      category.setText("Family Medicine");
		      
		      CodeableConceptDt reason = new CodeableConceptDt("SNOMED", "419772000");
		      comRequest.getReason().add(reason);
		      reason.getCodingFirstRep().setDisplay("NIH Coronary Heart Disease Risk Reminder");
		      
		      CodeableConceptDt priority = new CodeableConceptDt("CDS-System", "50");
		      priority.getCodingFirstRep().setDisplay("Routine");
		      comRequest.setPriority(priority);
		      
		      Provenance prov = createProvenance("http://www.nhlbi.nih.gov/health/health-topics/topics/hd");
		      ContainedDt contained = new ContainedDt();
			  contained.getContainedResources().add(prov);
		      comRequest.setContained(contained);
		      comRequest.addUndeclaredExtension(createOutputExtension());
		      prov.addUndeclaredExtension(createOutputExtension());
		      namedObjects.put("provenance", prov);	
		      namedObjects.put("communicationRequest", comRequest);			
end 
