--------------------------------------------------------
--  DDL for PCMM Types
--------------------------------------------------------

CREATE OR REPLACE TYPE PCMM.TEAMS_ROW FORCE AS OBJECT (
  TEAM_ID NUMBER,
  TEAM_NAME VARCHAR2(255),
  PCM_STD_TEAM_CARE_TYPE_ID NUMBER(20),
  STATIONNUMBER VARCHAR2(50),
  STAFF_IEN VARCHAR2(50)
);
/

CREATE OR REPLACE TYPE PCMM.TEAMS_TAB FORCE IS TABLE OF PCMM.TEAMS_ROW;
/

CREATE OR REPLACE TYPE PCMM.ROLES_ROW FORCE AS OBJECT (

  PCM_STD_TEAM_ROLE_ID NUMBER, 
  NAME VARCHAR2(255),
  STAFF_IEN VARCHAR2(50),
  STATIONNUMBER VARCHAR2(50)
);
/

CREATE OR REPLACE TYPE PCMM.ROLES_TAB FORCE IS TABLE OF PCMM.ROLES_ROW;
/
