DECLARE
  object_exists EXCEPTION;
  object_does_not_exist EXCEPTION;
  column_exists EXCEPTION;
  PRAGMA exception_init( object_exists, -955 );
  PRAGMA exception_init( object_does_not_exist, -942 );
  PRAGMA exception_init( column_exists, -1430 );
  PROCEDURE execute_ddl(ddl VARCHAR)
  IS
  BEGIN
    EXECUTE IMMEDIATE ddl;
    EXCEPTION
      WHEN object_exists THEN
        NULL;
      WHEN object_does_not_exist THEN
        NULL;
      WHEN column_exists THEN
        NULL;
      WHEN OTHERS THEN
        DBMS_OUTPUT.put_line ('ERROR - PCMM TABLES');
        DBMS_OUTPUT.put_line (SQLERRM);
        RAISE;
  END;

BEGIN

  execute_ddl('DROP VIEW PCMM.PATIENT_PRIMARY_CARE');
  execute_ddl('DROP TABLE PCMM.PATIENT_PCM');
  execute_ddl('
    CREATE TABLE PCMM.PATIENT_PRIMARY_CARE
    (
      ICN VARCHAR2(50),
      TEAM_ID NUMBER,
      TEAM_NAME VARCHAR2(255),
      TEAM_STATION_NUMBER VARCHAR2(50),
      STAFF_IEN VARCHAR2(50),
      STAFF_LAST_NAME VARCHAR2(255),
      STAFF_FIRST_NAME VARCHAR2(255),
      STAFF_MIDDLE_NAME VARCHAR2(255),
      TEAM_PATIENT_START_DATE DATE,
      TEAM_STAFF_START_DATE DATE
    )
    NOLOGGING
  ');

  execute_ddl('
    ALTER TABLE PCMM.PATIENT_PRIMARY_CARE
    ADD BASE_ICN VARCHAR2(50)
  ');

  execute_ddl('
    CREATE INDEX PCMM.PATIENT_PRIMARY_CARE_ICN_IDX ON PCMM.PATIENT_PRIMARY_CARE ("ICN")
    TABLESPACE "PCMM_X"
  ');

  execute_ddl('
    CREATE INDEX PCMM.PATIENT_PRIM_CARE_BASE_ICN_IDX ON PCMM.PATIENT_PRIMARY_CARE ("BASE_ICN")
    TABLESPACE "PCMM_X"
  ');

  execute_ddl('
    CREATE INDEX PCMM.PATIENT_PRIM_CARE_STATION_IDX ON PCMM.PATIENT_PRIMARY_CARE ("TEAM_STATION_NUMBER")
    TABLESPACE "PCMM_X"
  ');

  execute_ddl('
    CREATE TABLE PCMM.TEAM_STAFF_INST
    (
      TEAM_ID NUMBER(20, 0) NOT NULL,
      TEAM_POSITION_ID NUMBER(20, 0) NOT NULL,
      PCM_STD_TEAM_ROLE_ID NUMBER(20, 0) NOT NULL,
      STATIONNUMBER VARCHAR2(7),
      STAFF_IEN VARCHAR2(30),
      VA_INSTITUTION_ID NUMBER(20, 0),
      STAFF_ID NUMBER(20, 0) NOT NULL,
      FIRST_NAME VARCHAR2(30),
      MIDDLE_NAME VARCHAR2(30),
      LAST_NAME VARCHAR2(40) NOT NULL,
      PCM_STD_TEAM_CARE_TYPE_ID NUMBER(20, 0),
      PCM_STD_TEAM_FOCUS_CODE VARCHAR2(10)
    )
    NOLOGGING
  ');

  execute_ddl('
    CREATE INDEX PCMM.IDX_TSI_IEN_STATIONNUMBER ON PCMM.TEAM_STAFF_INST ("STAFF_IEN", "STATIONNUMBER")
    TABLESPACE "PCMM_X"
    ');
END;
/
