define([
    'backbone',
    'marionette',
    'jquery',
    'handlebars'
], function(Backbone, Marionette, $, Handlebars) {

    return [{
        id: 'fieldset',
        label: 'Fieldset',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: false,
        storyNumber: 6807,
        documentationURL: "/documentation/#/adk/form-controls#Wrappers-Fieldset"
    }, {
        id: 'container_showingModelData',
        label: 'Container - (supports displaying model data)',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: false,
        storyNumber: 7667,
        documentationURL: "/documentation/#/adk/form-controls#Wrappers-Container"
    }, {
        id: 'button',
        label: 'Button',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 6807,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Button"
    }, {
        id: 'dropdown',
        label: 'Dropdown',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 8072,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Dropdown"
    }, {
        id: 'input',
        label: 'Input',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 6807,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Input"
    }, {
        id: 'input_showUnit',
        label: 'Input - (supports showing units)',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 7541,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Input"
    }, {
        id: 'input_chooseUnitRadio',
        label: 'Input - (supports choosing unit with radio buttons)',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 7541,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Input"
    }, {
        id: 'input_chooseUnitDropdown',
        label: 'Input - (supports choosing unit with a select dropdown)',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 8170,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Input"
    }, {
        id: 'input_showCharacterCount',
        label: 'Input - (supports character count)',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 8073,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Input"
    }, {
        id: 'typeahead',
        label: 'Typeahead',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 7438,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Typeahead"
    }, {
        id: 'typeahead_footerButton',
        label: 'Typeahead (supports having an extend search button in the dropdown list)',
        developmentStatus: false,
        cometStatus: false,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 8395,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Typeahead"
    }, {
        id: 'typeahead_dynamicFetching',
        label: 'Typeahead (supports dynamic fetching of picklist items)',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 8402,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Typeahead"
    }, {
        id: 'radio',
        label: 'Radio',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 6807,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Radio"
    }, {
        id: 'checkbox',
        label: 'Checkbox',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 6807,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Checkbox"
    }, {
        id: 'checklist',
        label: 'Checklist',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 7629,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Checklist"
    }, {
        id: 'radioList',
        label: 'Radio List',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 7436,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Radio-List"
    }, {
        id: 'select',
        label: 'Select',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 6807,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Select"
    }, {
        id: 'select_showMultiple',
        label: 'Select (support showing multiple items at once)',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 7440,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Select"
    }, {
        id: 'select_filtering',
        label: 'Select - (supports filtering)',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 8070,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Select"
    }, {
        id: 'select_dynamicFetching',
        label: 'Select - (supports dynamic fetching of picklist items)',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 8071,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Select"
    }, {
        id: 'select_selectMultiple',
        label: 'Select - (supports selecting multiple items)',
        developmentStatus: false,
        cometStatus: false,
        exampleForm: false,
        supportsErrorMessage: true,
        storyNumber: 8069,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Select"
    }, {
        id: 'selectList',
        label: 'Select List',
        developmentStatus: false,
        cometStatus: false,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 13379,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Select-List"
    }, {
        id: 'multiselectSideBySide',
        label: 'Multi-Select Side By Side',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 7437,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Multiselect-Side-By-Side"
    }, {
        id: 'datepicker',
        label: 'Datepicker',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 7443,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Datepicker"
    }, {
        id: 'datejspicker',
        label: 'Datejspicker',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 9717,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Datejspicker"
    }, {
        id: 'timepicker',
        label: 'Timepicker',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 7445,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Timepicker"
    }, {
        id: 'textarea',
        label: 'Textarea',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: true,
        storyNumber: 6807,
        documentationURL: "/documentation/#/adk/form-controls#Basic-Textarea"
    }, {
        id: 'alertBanner',
        label: 'Alert Banner',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 7665,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Alert-Banner"
    }, {
        id: 'rangeSlider',
        label: 'Range Slider',
        developmentStatus: true,
        cometStatus: false,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 7542,
        documentationURL: "/documentation/#/adk/form-controls#Utility-Range-Slider"
    }, {
        id: 'tableSelectableRows',
        label: 'Table with Selectable Rows',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 7678,
        documentationURL: "/documentation/#/adk/form-controls#Special-Selectable-Table"
    }, {
        id: 'tabs',
        label: 'Tabs',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 7545,
        documentationURL: "/documentation/#/adk/form-controls#Wrappers-Tabs"
    }, {
        id: 'collapsableContainer',
        label: 'Collapsable Containers',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: false,
        storyNumber: 8422,
        documentationURL: "/documentation/#/adk/form-controls#Wrappers-Collapsible-Container"
    }, {
        id: 'popover',
        label: 'Popover Container',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: false,
        supportsErrorMessage: false,
        storyNumber: 8405,
        documentationURL: "/documentation/#/adk/form-controls#Wrappers-Popover"
    }, {
        id: 'nestedCommentBox',
        label: 'Nested Comment Box',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 7439,
        documentationURL: "/documentation/#/adk/form-controls#Special-Nested-Comment-Box"
    }, {
        id: 'commentBox',
        label: 'Comment Box',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 8091,
        documentationURL: "/documentation/#/adk/form-controls#Special-Comment-Box"
    }, {
        id: 'drilldownChecklist',
        label: 'Drilldown Checklist',
        developmentStatus: true,
        cometStatus: true,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 8989,
        documentationURL: "/documentation/#/adk/form-controls#Special-Drilldown-Checklist"
    }, {
        id: 'toggleOptionsChecklist',
        label: 'Toggle Options Checklist',
        developmentStatus: false,
        cometStatus: false,
        exampleForm: true,
        supportsErrorMessage: false,
        storyNumber: 8090,
        documentationURL: "/documentation/#/adk/form-controls#Special-Toggle-Options-Checklist"
    }];
});