package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Diagnosis implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String  id;
   private java.lang.String code;
   private java.lang.String description;

   public Diagnosis()
   {
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public Diagnosis(java.lang.String id, java.lang.String code,
         java.lang.String description)
   {
      this.id = id;
      this.code = code;
      this.description = description;
   }

}