package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DischargeSignal implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.Integer actionId;
   private java.lang.String actionText;
   private java.lang.String history;
   private java.lang.String executionUserId;
   private java.lang.String executionUserName;
   private java.lang.String executionDateTime;
   private vistacore.order.discharge.DischargeSignalData data;

   public DischargeSignal()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getActionId()
   {
      return this.actionId;
   }

   public void setActionId(java.lang.Integer actionId)
   {
      this.actionId = actionId;
   }

   public java.lang.String getActionText()
   {
      return this.actionText;
   }

   public void setActionText(java.lang.String actionText)
   {
      this.actionText = actionText;
   }

   public java.lang.String getHistory()
   {
      return this.history;
   }

   public void setHistory(java.lang.String history)
   {
      this.history = history;
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public java.lang.String getExecutionDateTime()
   {
      return this.executionDateTime;
   }

   public void setExecutionDateTime(java.lang.String executionDateTime)
   {
      this.executionDateTime = executionDateTime;
   }

   public vistacore.order.discharge.DischargeSignalData getData()
   {
      return this.data;
   }

   public void setData(vistacore.order.discharge.DischargeSignalData data)
   {
      this.data = data;
   }

   public DischargeSignal(java.lang.String name, java.lang.Integer actionId,
         java.lang.String actionText, java.lang.String history,
         java.lang.String executionUserId, java.lang.String executionUserName,
         java.lang.String executionDateTime, DischargeSignalData data)
   {
      this.name = name;
      this.actionId = actionId;
      this.actionText = actionText;
      this.history = history;
      this.executionUserId = executionUserId;
      this.executionUserName = executionUserName;
      this.executionDateTime = executionDateTime;
      this.data = data;
   }

}