package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class DischargeFollowup implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String uid;
   private java.lang.String patientUid;
   private java.lang.String authorUid;
   private java.lang.String domain;
   private java.lang.String subDomain;
   private vistacore.order.Visit visit;
   private java.lang.String referenceId;
   private java.lang.String createdDateTime;

   private vistacore.order.discharge.DischargeVprData data;

   public DischargeFollowup()
   {
   }

   public java.lang.String getUid()
   {
      return this.uid;
   }

   public void setUid(java.lang.String uid)
   {
      this.uid = uid;
   }

   public java.lang.String getPatientUid()
   {
      return this.patientUid;
   }

   public void setPatientUid(java.lang.String patientUid)
   {
      this.patientUid = patientUid;
   }

   public java.lang.String getAuthorUid()
   {
      return this.authorUid;
   }

   public void setAuthorUid(java.lang.String authorUid)
   {
      this.authorUid = authorUid;
   }

   public java.lang.String getDomain()
   {
      return this.domain;
   }

   public void setDomain(java.lang.String domain)
   {
      this.domain = domain;
   }

   public java.lang.String getSubDomain()
   {
      return this.subDomain;
   }

   public void setSubDomain(java.lang.String subDomain)
   {
      this.subDomain = subDomain;
   }

   public vistacore.order.Visit getVisit()
   {
      return this.visit;
   }

   public void setVisit(vistacore.order.Visit visit)
   {
      this.visit = visit;
   }

   public java.lang.String getReferenceId()
   {
      return this.referenceId;
   }

   public void setReferenceId(java.lang.String referenceId)
   {
      this.referenceId = referenceId;
   }

   public java.lang.String getCreatedDateTime()
   {
      return this.createdDateTime;
   }

   public void setCreatedDateTime(java.lang.String createdDateTime)
   {
      this.createdDateTime = createdDateTime;
   }

   public vistacore.order.discharge.DischargeVprData getData()
   {
      return this.data;
   }

   public void setData(vistacore.order.discharge.DischargeVprData data)
   {
      this.data = data;
   }

   public DischargeFollowup(java.lang.String uid, java.lang.String patientUid,
         java.lang.String authorUid, java.lang.String domain,
         java.lang.String subDomain, vistacore.order.Visit visit,
         java.lang.String referenceId, java.lang.String createdDateTime,
         vistacore.order.discharge.DischargeVprData data)
   {
      this.uid = uid;
      this.patientUid = patientUid;
      this.authorUid = authorUid;
      this.domain = domain;
      this.subDomain = subDomain;
      this.visit = visit;
      this.referenceId = referenceId;
      this.createdDateTime = createdDateTime;
      this.data = data;
   }

}