package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DischargeUpdateSignalData implements java.io.Serializable
{

   static final long serialVersionUID = 2L;

   private String dateTime;

   private String categoryName;

   private String patientClassName;

   private String primaryStopCode;

   private String secondaryStopCode;

   public DischargeUpdateSignalData()
   {
   }

   public String getDateTime() {
      return this.dateTime;
   }

   public void setDateTime(String dateTime) {
      this.dateTime = dateTime;
   }

   public String getCategoryName() {
      return this.categoryName;
   }

   public void setCategoryName(String categoryName) {
      this.categoryName = categoryName;
   }

   public String getPatientClassName() {
      return this.patientClassName;
   }

   public void setPatientClassName(String patientClassName) {
      this.patientClassName = patientClassName;
   }

   public String getPrimaryStopCode() {
      return this.primaryStopCode;
   }

   public void setPrimaryStopCode(String primaryStopCode) {
      this.primaryStopCode = primaryStopCode;
   }

   public String getSecondaryStopCode() {
      return this.secondaryStopCode;
   }

   public void setSecondaryStopCode(String secondaryStopCode) {
      this.secondaryStopCode = secondaryStopCode;
   }

   public DischargeUpdateSignalData(String dateTime, String categoryName, String patientClassName,
                                    String primaryStopCode, String secondaryStopCode) {
      this.dateTime = dateTime;
      this.categoryName = categoryName;
      this.patientClassName = patientClassName;
      this.primaryStopCode = primaryStopCode;
      this.secondaryStopCode = secondaryStopCode;
   }

}