package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DischargeVprData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String deceased;
   private java.lang.String lastUpdateTime;
   private java.lang.String facilityCode;
   private java.lang.String facilityName;
   private java.lang.String reasonName;
   private java.lang.String specialty;

   private java.lang.String kind;

   private java.lang.String locationDisplayName;

   private java.lang.String locationName;

   private java.lang.String locationUid;

   private java.lang.String roomBed;

   private java.lang.String service;

   private java.lang.String shortLocationName;

   private java.lang.String stampTime;

   private java.util.List<vistacore.order.discharge.Movement> movements;

   private java.lang.String primaryDiagnosis;

   private java.lang.String primaryDiagnosisCode;

   private java.util.List<vistacore.order.discharge.Diagnosis> secondaryDiagnoses;

   private vistacore.order.discharge.DischargeProvider primaryProvider;

   private java.util.List<vistacore.order.discharge.DischargeProvider> providers;

   private vistacore.order.discharge.Stay stay;

   private java.lang.String icn;

   public DischargeVprData()
   {
   }

   public java.lang.String getDeceased()
   {
      return this.deceased;
   }

   public void setDeceased(java.lang.String deceased)
   {
      this.deceased = deceased;
   }

   public java.lang.String getLastUpdateTime()
   {
      return this.lastUpdateTime;
   }

   public void setLastUpdateTime(java.lang.String lastUpdateTime)
   {
      this.lastUpdateTime = lastUpdateTime;
   }

   public java.lang.String getFacilityCode()
   {
      return this.facilityCode;
   }

   public void setFacilityCode(java.lang.String facilityCode)
   {
      this.facilityCode = facilityCode;
   }

   public java.lang.String getFacilityName()
   {
      return this.facilityName;
   }

   public void setFacilityName(java.lang.String facilityName)
   {
      this.facilityName = facilityName;
   }

   public java.lang.String getReasonName()
   {
      return this.reasonName;
   }

   public void setReasonName(java.lang.String reasonName)
   {
      this.reasonName = reasonName;
   }

   public java.lang.String getSpecialty()
   {
      return this.specialty;
   }

   public void setSpecialty(java.lang.String specialty)
   {
      this.specialty = specialty;
   }

   public java.lang.String getKind()
   {
      return this.kind;
   }

   public void setKind(java.lang.String kind)
   {
      this.kind = kind;
   }

   public java.lang.String getLocationDisplayName()
   {
      return this.locationDisplayName;
   }

   public void setLocationDisplayName(java.lang.String locationDisplayName)
   {
      this.locationDisplayName = locationDisplayName;
   }

   public java.lang.String getLocationName()
   {
      return this.locationName;
   }

   public void setLocationName(java.lang.String locationName)
   {
      this.locationName = locationName;
   }

   public java.lang.String getLocationUid()
   {
      return this.locationUid;
   }

   public void setLocationUid(java.lang.String locationUid)
   {
      this.locationUid = locationUid;
   }

   public java.lang.String getRoomBed()
   {
      return this.roomBed;
   }

   public void setRoomBed(java.lang.String roomBed)
   {
      this.roomBed = roomBed;
   }

   public java.lang.String getService()
   {
      return this.service;
   }

   public void setService(java.lang.String service)
   {
      this.service = service;
   }

   public java.lang.String getShortLocationName()
   {
      return this.shortLocationName;
   }

   public void setShortLocationName(java.lang.String shortLocationName)
   {
      this.shortLocationName = shortLocationName;
   }

   public java.lang.String getStampTime()
   {
      return this.stampTime;
   }

   public void setStampTime(java.lang.String stampTime)
   {
      this.stampTime = stampTime;
   }

   public java.util.List<vistacore.order.discharge.Movement> getMovements()
   {
      return this.movements;
   }

   public void setMovements(
         java.util.List<vistacore.order.discharge.Movement> movements)
   {
      this.movements = movements;
   }

   public java.lang.String getPrimaryDiagnosis()
   {
	   return primaryDiagnosis;
   }

   public void setPrimaryDiagnosis(java.lang.String primaryDiagnosis)
	{
		this.primaryDiagnosis = primaryDiagnosis;
	}

	public java.lang.String getPrimaryDiagnosisCode()
	{
		return primaryDiagnosisCode;
	}

	public void setPrimaryDiagnosisCode(java.lang.String primaryDiagnosisCode)
	{
		this.primaryDiagnosisCode = primaryDiagnosisCode;
	}

	public java.util.List<vistacore.order.discharge.Diagnosis> getSecondaryDiagnoses()
	{
		return secondaryDiagnoses;
	}

	public void setSecondaryDiagnoses(java.util.List<vistacore.order.discharge.Diagnosis> secondaryDiagnoses)
	{
		this.secondaryDiagnoses = secondaryDiagnoses;
	}

	public vistacore.order.discharge.DischargeProvider getPrimaryProvider()
   {
      return this.primaryProvider;
   }

   public void setPrimaryProvider(
         vistacore.order.discharge.DischargeProvider primaryProvider)
   {
      this.primaryProvider = primaryProvider;
   }

   public java.util.List<vistacore.order.discharge.DischargeProvider> getProviders()
   {
      return this.providers;
   }

   public void setProviders(
         java.util.List<vistacore.order.discharge.DischargeProvider> providers)
   {
      this.providers = providers;
   }

   public vistacore.order.discharge.Stay getStay()
   {
      return this.stay;
   }

   public void setStay(vistacore.order.discharge.Stay stay)
   {
      this.stay = stay;
   }

   public java.lang.String getIcn()
   {
      return this.icn;
   }

   public void setIcn(java.lang.String icn)
   {
      this.icn = icn;
   }

   public DischargeVprData(java.lang.String deceased, java.lang.String lastUpdateTime,
         java.lang.String facilityCode, java.lang.String facilityName,
         java.lang.String reasonName, java.lang.String specialty,
         java.lang.String kind, java.lang.String locationDisplayName,
         java.lang.String locationName, java.lang.String locationUid,
         java.lang.String roomBed, java.lang.String service,
         java.lang.String shortLocationName, java.lang.String stampTime,
         java.util.List<vistacore.order.discharge.Movement> movements,
         java.lang.String primaryDiagnosis, java.lang.String primaryDiagnosisCode,
         java.util.List<vistacore.order.discharge.Diagnosis> secondaryDiagnoses,
         vistacore.order.discharge.DischargeProvider primaryProvider,
         java.util.List<vistacore.order.discharge.DischargeProvider> providers,
         vistacore.order.discharge.Stay stay,
         java.lang.String icn)
   {
      this.deceased = deceased;
      this.lastUpdateTime = lastUpdateTime;
      this.facilityCode = facilityCode;
      this.facilityName = facilityName;
      this.reasonName = reasonName;
      this.specialty = specialty;
      this.kind = kind;
      this.locationDisplayName = locationDisplayName;
      this.locationName = locationName;
      this.locationUid = locationUid;
      this.roomBed = roomBed;
      this.service = service;
      this.shortLocationName = shortLocationName;
      this.stampTime = stampTime;
      this.movements = movements;
      this.primaryDiagnosis = primaryDiagnosis;
      this.primaryDiagnosisCode = primaryDiagnosisCode;
      this.secondaryDiagnoses = secondaryDiagnoses;
      this.primaryProvider = primaryProvider;
      this.providers = providers;
      this.stay = stay;
      this.icn = icn;
   }

}