package vistacore.order.discharge;

import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DischargeData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private vistacore.order.discharge.DischargeActivity activity;
   private vistacore.order.discharge.Discharge discharge;
   private vistacore.order.discharge.DischargeContact contact;
   @com.google.gson.annotations.SerializedName("follow-up")
   private java.util.List<vistacore.order.discharge.Followup> followup = new ArrayList<>();
   private java.util.List<vistacore.order.discharge.DischargeSignal> signals = new ArrayList<>();

   public DischargeData()
   {
   }

   public vistacore.order.discharge.Discharge getDischarge()
   {
      return this.discharge;
   }

   public void setDischarge(vistacore.order.discharge.Discharge discharge)
   {
      this.discharge = discharge;
   }

   public vistacore.order.discharge.DischargeContact getContact()
   {
      return this.contact;
   }

   public void setContact(vistacore.order.discharge.DischargeContact contact)
   {
      this.contact = contact;
   }

   public java.util.List<vistacore.order.discharge.Followup> getFollowup()
   {
      return this.followup;
   }

   public void setFollowup(
         java.util.List<vistacore.order.discharge.Followup> followup)
   {
      this.followup = followup;
   }

   public java.util.List<vistacore.order.discharge.DischargeSignal> getSignals()
   {
      return this.signals;
   }

   public void setSignals(
         java.util.List<vistacore.order.discharge.DischargeSignal> signals)
   {
      this.signals = signals;
   }

   public vistacore.order.discharge.DischargeActivity getActivity()
   {
      return this.activity;
   }

   public void setActivity(vistacore.order.discharge.DischargeActivity activity)
   {
      this.activity = activity;
   }

   public DischargeData(vistacore.order.discharge.DischargeActivity activity,
         vistacore.order.discharge.Discharge discharge,
         vistacore.order.discharge.DischargeContact contact,
         java.util.List<vistacore.order.discharge.Followup> followup,
         java.util.List<vistacore.order.discharge.DischargeSignal> signals)
   {
      this.activity = activity;
      this.discharge = discharge;
      this.contact = contact;
      this.followup = followup;
      this.signals = signals;
   }

}