package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DischargeSignalData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String comment;

   public DischargeSignalData()
   {
   }

   public String getComment()
   {
      return this.comment;
   }

   public void setComment(String comment)
   {
      this.comment = comment;
   }

   public DischargeSignalData(String comment)
   {
      this.comment = comment;
   }

}