package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Discharge implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String dateTime;
   private java.lang.String date;
   private java.lang.String admitDateTime;
   private java.lang.String fromFacilityId;
   private java.lang.String disposition;
   private java.lang.String timeout;

   private java.util.List<vistacore.order.discharge.Diagnosis> diagnosis;

   private java.lang.String fromFacilityDescription;

   private java.lang.String primaryCarePhysicianNameAtDischarge;

   private java.lang.String primaryCareTeamAtDischarge;

   public Discharge()
   {
   }

   public java.lang.String getFromFacilityId()
   {
      return this.fromFacilityId;
   }

   public void setFromFacilityId(java.lang.String fromFacilityId)
   {
      this.fromFacilityId = fromFacilityId;
   }

   public java.lang.String getDisposition()
   {
      return this.disposition;
   }

   public void setDisposition(java.lang.String disposition)
   {
      this.disposition = disposition;
   }

   public java.lang.String getTimeout()
   {
      return this.timeout;
   }

   public void setTimeout(java.lang.String timeout)
   {
      this.timeout = timeout;
   }

   public java.util.List<vistacore.order.discharge.Diagnosis> getDiagnosis()
   {
      return this.diagnosis;
   }

   public void setDiagnosis(
         java.util.List<vistacore.order.discharge.Diagnosis> diagnosis)
   {
      this.diagnosis = diagnosis;
   }

   public java.lang.String getDate()
   {
      return this.date;
   }

   private void setDate(java.lang.String date)
   {
      if(date != null && !date.isEmpty()) {
         this.date = date.substring(0, 8);
      }
   }

   public java.lang.String getDateTime()
   {
      return this.dateTime;
   }

   public void setDateTime(java.lang.String dateTime)
   {
      this.dateTime = dateTime;
      this.setDate(dateTime);
   }

   public java.lang.String getAdmitDateTime()
   {
      return this.admitDateTime;
   }

   public void setAdmitDateTime(java.lang.String admitDateTime)
   {
      this.admitDateTime = admitDateTime;
   }

   public java.lang.String getFromFacilityDescription()
   {
      return this.fromFacilityDescription;
   }

   public void setFromFacilityDescription(java.lang.String fromFacilityDescription)
   {
      this.fromFacilityDescription = fromFacilityDescription;
   }

   public java.lang.String getPrimaryCarePhysicianNameAtDischarge()
   {
      return this.primaryCarePhysicianNameAtDischarge;
   }

   public void setPrimaryCarePhysicianNameAtDischarge(
         java.lang.String primaryCarePhysicianNameAtDischarge)
   {
      this.primaryCarePhysicianNameAtDischarge = primaryCarePhysicianNameAtDischarge;
   }

   public java.lang.String getPrimaryCareTeamAtDischarge()
   {
      return this.primaryCareTeamAtDischarge;
   }

   public void setPrimaryCareTeamAtDischarge(
         java.lang.String primaryCareTeamAtDischarge)
   {
      this.primaryCareTeamAtDischarge = primaryCareTeamAtDischarge;
   }

   public Discharge(java.lang.String dateTime, java.lang.String admitDateTime,
         java.lang.String fromFacilityId, java.lang.String disposition,
         java.lang.String timeout,
         java.util.List<vistacore.order.discharge.Diagnosis> diagnosis,
         java.lang.String fromFacilityDescription,
         java.lang.String primaryCarePhysicianNameAtDischarge,
         java.lang.String primaryCareTeamAtDischarge)
   {
      this.dateTime = dateTime;
      this.setDate(dateTime);
      this.admitDateTime = admitDateTime;
      this.fromFacilityId = fromFacilityId;
      this.disposition = disposition;
      this.timeout = timeout;
      this.diagnosis = diagnosis;
      this.fromFacilityDescription = fromFacilityDescription;
      this.primaryCarePhysicianNameAtDischarge = primaryCarePhysicianNameAtDischarge;
      this.primaryCareTeamAtDischarge = primaryCareTeamAtDischarge;
   }

}