package vistacore.order.discharge;

import vistacore.order.Activity;

import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DischargeActivity extends Activity implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<vistacore.order.discharge.Health> health = new ArrayList<>();

   private java.lang.String patientName;

   public DischargeActivity()
   {
   }

   public java.util.List<vistacore.order.discharge.Health> getHealth()
   {
      return this.health;
   }

   public void setHealth(
         java.util.List<vistacore.order.discharge.Health> health)
   {
      this.health = health;
   }

   public java.lang.String getPatientName()
   {
      return this.patientName;
   }

   public void setPatientName(java.lang.String patientName)
   {
      this.patientName = patientName;
   }

   public DischargeActivity(
         java.util.List<vistacore.order.discharge.Health> health,
         java.lang.String patientName)
   {
      this.health = health;
      this.patientName = patientName;
   }

}