package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DischargeProvider implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String providerDisplayName;
   private java.lang.String providerName;
   private java.lang.String providerUid;
   private java.lang.String role;
   private java.lang.String summary;
   private java.lang.String primary;

   public DischargeProvider()
   {
   }

   public java.lang.String getProviderDisplayName()
   {
      return this.providerDisplayName;
   }

   public void setProviderDisplayName(java.lang.String providerDisplayName)
   {
      this.providerDisplayName = providerDisplayName;
   }

   public java.lang.String getProviderName()
   {
      return this.providerName;
   }

   public void setProviderName(java.lang.String providerName)
   {
      this.providerName = providerName;
   }

   public java.lang.String getProviderUid()
   {
      return this.providerUid;
   }

   public void setProviderUid(java.lang.String providerUid)
   {
      this.providerUid = providerUid;
   }

   public java.lang.String getRole()
   {
      return this.role;
   }

   public void setRole(java.lang.String role)
   {
      this.role = role;
   }

   public java.lang.String getSummary()
   {
      return this.summary;
   }

   public void setSummary(java.lang.String summary)
   {
      this.summary = summary;
   }

   public java.lang.String getPrimary()
   {
      return this.primary;
   }

   public void setPrimary(java.lang.String primary)
   {
      this.primary = primary;
   }

   public DischargeProvider(java.lang.String providerDisplayName,
         java.lang.String providerName, java.lang.String providerUid,
         java.lang.String role, java.lang.String summary,
         java.lang.String primary)
   {
      this.providerDisplayName = providerDisplayName;
      this.providerName = providerName;
      this.providerUid = providerUid;
      this.role = role;
      this.summary = summary;
      this.primary = primary;
   }

}