package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Followup implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String actionId;
   private java.lang.String actionText;
   private java.lang.String executionUserId;
   private java.lang.String executionUserName;
   private java.lang.String executionDateTime;
   private vistacore.order.Visit visit;
   private java.lang.String comment;
   private java.lang.String attempt;

   public Followup()
   {
   }

   public java.lang.String getActionId()
   {
      return this.actionId;
   }

   public void setActionId(java.lang.String actionId)
   {
      this.actionId = actionId;
   }

   public java.lang.String getActionText()
   {
      return this.actionText;
   }

   public void setActionText(java.lang.String actionText)
   {
      this.actionText = actionText;
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public java.lang.String getExecutionDateTime()
   {
      return this.executionDateTime;
   }

   public void setExecutionDateTime(java.lang.String executionDateTime)
   {
      this.executionDateTime = executionDateTime;
   }

   public vistacore.order.Visit getVisit()
   {
      return this.visit;
   }

   public void setVisit(vistacore.order.Visit visit)
   {
      this.visit = visit;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public java.lang.String getAttempt()
   {
      return this.attempt;
   }

   public void setAttempt(java.lang.String attempt)
   {
      this.attempt = attempt;
   }

   public Followup(java.lang.String actionId, java.lang.String actionText,
         java.lang.String executionUserId, java.lang.String executionUserName,
         java.lang.String executionDateTime, vistacore.order.Visit visit,
         java.lang.String comment, java.lang.String attempt)
   {
      this.actionId = actionId;
      this.actionText = actionText;
      this.executionUserId = executionUserId;
      this.executionUserName = executionUserName;
      this.executionDateTime = executionDateTime;
      this.visit = visit;
      this.comment = comment;
      this.attempt = attempt;
   }

}