package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Health implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.Boolean isHealthy;
   private java.lang.String description;
   private java.lang.Integer importance;

   public Health()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.Boolean getIsHealthy()
   {
      return this.isHealthy;
   }

   public void setIsHealthy(java.lang.Boolean isHealthy)
   {
      this.isHealthy = isHealthy;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.Integer getImportance()
   {
      return this.importance;
   }

   public void setImportance(java.lang.Integer importance)
   {
      this.importance = importance;
   }

   public Health(java.lang.String id, java.lang.Boolean isHealthy,
         java.lang.String description, java.lang.Integer importance)
   {
      this.id = id;
      this.isHealthy = isHealthy;
      this.description = description;
      this.importance = importance;
   }

}