package vistacore.order.discharge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Stay implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String arrivalDateTime;
   private java.lang.String dischargeDateTime;

   public Stay()
   {
   }

   public java.lang.String getArrivalDateTime()
   {
      return this.arrivalDateTime;
   }

   public void setArrivalDateTime(java.lang.String arrivalDateTime)
   {
      this.arrivalDateTime = arrivalDateTime;
   }

   public java.lang.String getDischargeDateTime()
   {
      return this.dischargeDateTime;
   }

   public void setDischargeDateTime(java.lang.String dischargeDateTime)
   {
      this.dischargeDateTime = dischargeDateTime;
   }

   public Stay(java.lang.String arrivalDateTime,
         java.lang.String dischargeDateTime)
   {
      this.arrivalDateTime = arrivalDateTime;
      this.dischargeDateTime = dischargeDateTime;
   }

}