package vistacore.order.request;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestActivity implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String uid;
   private java.lang.String patientUid;
   private java.lang.String authorUid;
   private java.lang.String domain;
   private java.lang.String subDomain;
   private vistacore.order.Visit visit;
   private java.lang.String ehmpState;
   private java.lang.String displayName;
   private java.lang.String referenceId;
   private vistacore.order.request.RequestData data;

   private java.lang.String formAction;

   private java.lang.String creationDateTime;

   private java.lang.String instanceName;

   private java.lang.Integer urgency;

   public RequestActivity()
   {
   }

   public java.lang.String getUid()
   {
      return this.uid;
   }

   public void setUid(java.lang.String uid)
   {
      this.uid = uid;
   }

   public java.lang.String getPatientUid()
   {
      return this.patientUid;
   }

   public void setPatientUid(java.lang.String patientUid)
   {
      this.patientUid = patientUid;
   }

   public java.lang.String getAuthorUid()
   {
      return this.authorUid;
   }

   public void setAuthorUid(java.lang.String authorUid)
   {
      this.authorUid = authorUid;
   }

   public java.lang.String getDomain()
   {
      return this.domain;
   }

   public void setDomain(java.lang.String domain)
   {
      this.domain = domain;
   }

   public java.lang.String getSubDomain()
   {
      return this.subDomain;
   }

   public void setSubDomain(java.lang.String subDomain)
   {
      this.subDomain = subDomain;
   }

   public vistacore.order.Visit getVisit()
   {
      return this.visit;
   }

   public void setVisit(vistacore.order.Visit visit)
   {
      this.visit = visit;
   }

   public java.lang.String getEhmpState()
   {
      return this.ehmpState;
   }

   public void setEhmpState(java.lang.String ehmpState)
   {
      this.ehmpState = ehmpState;
   }

   public java.lang.String getDisplayName()
   {
      return this.displayName;
   }

   public void setDisplayName(java.lang.String displayName)
   {
      this.displayName = displayName;
   }

   public java.lang.String getReferenceId()
   {
      return this.referenceId;
   }

   public void setReferenceId(java.lang.String referenceId)
   {
      this.referenceId = referenceId;
   }

   public vistacore.order.request.RequestData getData()
   {
      return this.data;
   }

   public void setData(vistacore.order.request.RequestData data)
   {
      this.data = data;
   }

   public java.lang.String getFormAction()
   {
      return this.formAction;
   }

   public void setFormAction(java.lang.String formAction)
   {
      this.formAction = formAction;
   }

   public java.lang.String getCreationDateTime()
   {
      return this.creationDateTime;
   }

   public void setCreationDateTime(java.lang.String creationDateTime)
   {
      this.creationDateTime = creationDateTime;
   }

   public java.lang.String getInstanceName()
   {
      return this.instanceName;
   }

   public void setInstanceName(java.lang.String instanceName)
   {
      this.instanceName = instanceName;
   }

   public java.lang.Integer getUrgency()
   {
      return this.urgency;
   }

   public void setUrgency(java.lang.Integer urgency)
   {
      this.urgency = urgency;
   }

   public RequestActivity(java.lang.String uid, java.lang.String patientUid,
         java.lang.String authorUid, java.lang.String domain,
         java.lang.String subDomain, vistacore.order.Visit visit,
         java.lang.String ehmpState, java.lang.String displayName,
         java.lang.String referenceId, vistacore.order.request.RequestData data,
         java.lang.String formAction, java.lang.String creationDateTime,
         java.lang.String instanceName, java.lang.Integer urgency)
   {
      this.uid = uid;
      this.patientUid = patientUid;
      this.authorUid = authorUid;
      this.domain = domain;
      this.subDomain = subDomain;
      this.visit = visit;
      this.ehmpState = ehmpState;
      this.displayName = displayName;
      this.referenceId = referenceId;
      this.data = data;
      this.formAction = formAction;
      this.creationDateTime = creationDateTime;
      this.instanceName = instanceName;
      this.urgency = urgency;
   }
}