package vistacore.order.request;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Request implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String urgency;
   private java.lang.String earliestDate;
   private java.lang.String latestDate;
   private java.lang.String title;
   private java.lang.String taskInstanceId;
   private java.lang.String urgencyId;
   private java.lang.String assignTo;
   private java.lang.String request;
   private java.lang.String submittedTimeStamp;
   private vistacore.order.Visit visit;

   private vistacore.order.request.Route route;

   private java.lang.String routingCode;

   private java.lang.String submittedByUid;

   private java.lang.String submittedByName;

   private java.lang.String comment;

   private java.lang.String action;

   public Request()
   {
   }

   public String getUrgency()
   {
      return urgency;
   }

   public void setUrgency(String urgency)
   {
      this.urgency = urgency;
   }

   public String getEarliestDate()
   {
      return earliestDate;
   }

   public void setEarliestDate(String earliestDate)
   {
      this.earliestDate = earliestDate;
   }

   public String getLatestDate()
   {
      return latestDate;
   }

   public void setLatestDate(String latestDate)
   {
      this.latestDate = latestDate;
   }

   public String getTitle()
   {
      return title;
   }

   public void setTitle(String title)
   {
      this.title = title;
   }

   public String getTaskInstanceId()
   {
      return taskInstanceId;
   }

   public void setTaskInstanceId(String taskInstanceId)
   {
      this.taskInstanceId = taskInstanceId;
   }

   public String getUrgencyId()
   {
      return urgencyId;
   }

   public void setUrgencyId(String urgencyId)
   {
      this.urgencyId = urgencyId;
   }

   public String getAssignTo()
   {
      return assignTo;
   }

   public void setAssignTo(String assignTo)
   {
      this.assignTo = assignTo;
   }

   public String getRequest()
   {
      return request;
   }

   public void setRequest(String request)
   {
      this.request = request;
   }

   public String getSubmittedTimeStamp()
   {
      return submittedTimeStamp;
   }

   public void setSubmittedTimeStamp(String submittedTimeStamp)
   {
      this.submittedTimeStamp = submittedTimeStamp;
   }

   public vistacore.order.Visit getVisit()
   {
      return this.visit;
   }

   public void setVisit(vistacore.order.Visit visit)
   {
      this.visit = visit;
   }

   public vistacore.order.request.Route getRoute()
   {
      return this.route;
   }

   public void setRoute(vistacore.order.request.Route route)
   {
      this.route = route;
   }

   public java.lang.String getRoutingCode()
   {
      return this.routingCode;
   }

   public void setRoutingCode(java.lang.String routingCode)
   {
      this.routingCode = routingCode;
   }

   public java.lang.String getSubmittedByUid()
   {
      return this.submittedByUid;
   }

   public void setSubmittedByUid(java.lang.String submittedByUid)
   {
      this.submittedByUid = submittedByUid;
   }

   public java.lang.String getSubmittedByName()
   {
      return this.submittedByName;
   }

   public void setSubmittedByName(java.lang.String submittedByName)
   {
      this.submittedByName = submittedByName;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public java.lang.String getAction()
   {
      return this.action;
   }

   public void setAction(java.lang.String action)
   {
      this.action = action;
   }

   public Request(java.lang.String urgency, java.lang.String earliestDate,
         java.lang.String latestDate, java.lang.String title,
         java.lang.String taskInstanceId, java.lang.String urgencyId,
         java.lang.String assignTo, java.lang.String request,
         java.lang.String submittedTimeStamp, vistacore.order.Visit visit,
         vistacore.order.request.Route route, java.lang.String routingCode,
         java.lang.String submittedByUid, java.lang.String submittedByName,
         java.lang.String comment, java.lang.String action)
   {
      this.urgency = urgency;
      this.earliestDate = earliestDate;
      this.latestDate = latestDate;
      this.title = title;
      this.taskInstanceId = taskInstanceId;
      this.urgencyId = urgencyId;
      this.assignTo = assignTo;
      this.request = request;
      this.submittedTimeStamp = submittedTimeStamp;
      this.visit = visit;
      this.route = route;
      this.routingCode = routingCode;
      this.submittedByUid = submittedByUid;
      this.submittedByName = submittedByName;
      this.comment = comment;
      this.action = action;
   }

}