package vistacore.order.request;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestSignalData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String comment;

   public RequestSignalData()
   {
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public RequestSignalData(java.lang.String comment)
   {
      this.comment = comment;
   }

}