package vistacore.order.request;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestSignal implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String actionText;
   private java.lang.String history;
   private java.lang.String executionUserName;
   private java.lang.String executionUserId;
   private java.lang.String executionDateTime;
   private java.lang.String actionId;

   private vistacore.order.request.RequestSignalData data;

   public RequestSignal()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getHistory()
   {
      return this.history;
   }

   public void setHistory(java.lang.String history)
   {
      this.history = history;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionDateTime()
   {
      return this.executionDateTime;
   }

   public void setExecutionDateTime(java.lang.String executionDateTime)
   {
      this.executionDateTime = executionDateTime;
   }

   public java.lang.String getActionText()
   {
      return this.actionText;
   }

   public void setActionText(java.lang.String actionText)
   {
      this.actionText = actionText;
   }

   public java.lang.String getActionId()
   {
      return this.actionId;
   }

   public void setActionId(java.lang.String actionId)
   {
      this.actionId = actionId;
   }

   public vistacore.order.request.RequestSignalData getData()
   {
      return this.data;
   }

   public void setData(vistacore.order.request.RequestSignalData data)
   {
      this.data = data;
   }

   public RequestSignal(java.lang.String name, java.lang.String actionText,
         java.lang.String history, java.lang.String executionUserName,
         java.lang.String executionUserId, java.lang.String executionDateTime,
         java.lang.String actionId, vistacore.order.request.RequestSignalData data)
   {
      this.name = name;
      this.actionText = actionText;
      this.history = history;
      this.executionUserName = executionUserName;
      this.executionUserId = executionUserId;
      this.executionDateTime = executionDateTime;
      this.actionId = actionId;
      this.data = data;
   }

}