package vistacore.order.request;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Route implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String facility;

   private java.lang.String person;

   private vistacore.order.request.RequestIdentifier team;

   private java.lang.Boolean patientAssignment;

   private java.util.List<vistacore.order.request.RequestIdentifier> assignedRoles;

   private java.lang.String routingCode;

   private vistacore.order.request.RequestIdentifier teamCareType;

   private java.lang.String facilityName;

   private java.lang.String personName;

   public Route()
   {
   }

   public java.lang.String getFacility()
   {
      return this.facility;
   }

   public void setFacility(java.lang.String facility)
   {
      this.facility = facility;
   }

   public java.lang.String getPerson()
   {
      return this.person;
   }

   public void setPerson(java.lang.String person)
   {
      this.person = person;
   }

   public vistacore.order.request.RequestIdentifier getTeam()
   {
      return this.team;
   }

   public void setTeam(vistacore.order.request.RequestIdentifier team)
   {
      this.team = team;
   }

   public java.lang.Boolean getPatientAssignment()
   {
      return this.patientAssignment;
   }

   public void setPatientAssignment(java.lang.Boolean patientAssignment)
   {
      this.patientAssignment = patientAssignment;
   }

   public java.util.List<vistacore.order.request.RequestIdentifier> getAssignedRoles()
   {
      return this.assignedRoles;
   }

   public void setAssignedRoles(
         java.util.List<vistacore.order.request.RequestIdentifier> assignedRoles)
   {
      this.assignedRoles = assignedRoles;
   }

   public java.lang.String getRoutingCode()
   {
      return this.routingCode;
   }

   public void setRoutingCode(java.lang.String routingCode)
   {
      this.routingCode = routingCode;
   }

   public vistacore.order.request.RequestIdentifier getTeamCareType()
   {
      return this.teamCareType;
   }

   public void setTeamCareType(vistacore.order.request.RequestIdentifier teamCareType)
   {
      this.teamCareType = teamCareType;
   }

   public java.lang.String getFacilityName()
   {
      return this.facilityName;
   }

   public void setFacilityName(java.lang.String facilityName)
   {
      this.facilityName = facilityName;
   }

   public java.lang.String getPersonName()
   {
      return this.personName;
   }

   public void setPersonName(java.lang.String personName)
   {
      this.personName = personName;
   }

   public Route(
         java.lang.String facility,
         java.lang.String person,
         vistacore.order.request.RequestIdentifier team,
         java.lang.Boolean patientAssignment,
         java.util.List<vistacore.order.request.RequestIdentifier> assignedRoles,
         java.lang.String routingCode,
         vistacore.order.request.RequestIdentifier teamCareType,
         java.lang.String facilityName, java.lang.String personName)
   {
      this.facility = facility;
      this.person = person;
      this.team = team;
      this.patientAssignment = patientAssignment;
      this.assignedRoles = assignedRoles;
      this.routingCode = routingCode;
      this.teamCareType = teamCareType;
      this.facilityName = facilityName;
      this.personName = personName;
   }

}