
package gov.va.med.jmeadows_2_3_1.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "JMeadowsData", targetNamespace = "http://webservice.jmeadows.domain.ext/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JMeadowsData {


    /**
     * 
     * @param siteCode
     * @param verifyCode
     * @param accessCode
     * @param requestingApp
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.User
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.LoginResponse")
    public User login(
            @WebParam(name = "siteCode", targetNamespace = "")
            String siteCode,
            @WebParam(name = "accessCode", targetNamespace = "")
            String accessCode,
            @WebParam(name = "verifyCode", targetNamespace = "")
            String verifyCode,
            @WebParam(name = "requestingApp", targetNamespace = "")
            String requestingApp)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param authUserInfoQuery
     * @return
     *     returns boolean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserSubjectDN", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.UpdateUserSubjectDN")
    @ResponseWrapper(localName = "updateUserSubjectDNResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.UpdateUserSubjectDNResponse")
    public boolean updateUserSubjectDN(
            @WebParam(name = "authUserInfoQuery", targetNamespace = "")
            AuthUserInfo authUserInfoQuery)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param siteCode
     * @param verifyCode
     * @param cardID
     * @param accessCode
     * @param ipAddress
     * @param requestingApp
     * @param subjectDN
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.User
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginEnterprise", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.LoginEnterprise")
    @ResponseWrapper(localName = "loginEnterpriseResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.LoginEnterpriseResponse")
    public User loginEnterprise(
            @WebParam(name = "cardID", targetNamespace = "")
            String cardID,
            @WebParam(name = "siteCode", targetNamespace = "")
            String siteCode,
            @WebParam(name = "accessCode", targetNamespace = "")
            String accessCode,
            @WebParam(name = "verifyCode", targetNamespace = "")
            String verifyCode,
            @WebParam(name = "requestingApp", targetNamespace = "")
            String requestingApp,
            @WebParam(name = "ipAddress", targetNamespace = "")
            String ipAddress,
            @WebParam(name = "subjectDN", targetNamespace = "")
            String subjectDN)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Patient>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lookupPatient", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.LookupPatient")
    @ResponseWrapper(localName = "lookupPatientResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.LookupPatientResponse")
    public List<Patient> lookupPatient(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.ResponsePatientQuery
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lookupPatientPDWS", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.LookupPatientPDWS")
    @ResponseWrapper(localName = "lookupPatientPDWSResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.LookupPatientPDWSResponse")
    public ResponsePatientQuery lookupPatientPDWS(
            @WebParam(name = "queryBean", targetNamespace = "")
            PdwsQueryBean queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.Patient
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPatient", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SelectPatient")
    @ResponseWrapper(localName = "selectPatientResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SelectPatientResponse")
    public Patient selectPatient(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.ResponsePatientSelect
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPatientMVI", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SelectPatientMVI")
    @ResponseWrapper(localName = "selectPatientMVIResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SelectPatientMVIResponse")
    public ResponsePatientSelect selectPatientMVI(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "selectPatientForVASensitive", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SelectPatientForVASensitive")
    @ResponseWrapper(localName = "selectPatientForVASensitiveResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SelectPatientForVASensitiveResponse")
    public void selectPatientForVASensitive(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "auditVARestrictedAccess", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.AuditVARestrictedAccess")
    @ResponseWrapper(localName = "auditVARestrictedAccessResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.AuditVARestrictedAccessResponse")
    public void auditVARestrictedAccess(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "auditSensitiveRecordAccess", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.AuditSensitiveRecordAccess")
    @ResponseWrapper(localName = "auditSensitiveRecordAccessResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.AuditSensitiveRecordAccessResponse")
    public void auditSensitiveRecordAccess(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.PatientAdmission>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientAdmissions", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientAdmissions")
    @ResponseWrapper(localName = "getPatientAdmissionsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientAdmissionsResponse")
    public List<PatientAdmission> getPatientAdmissions(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.PatientHistory>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientHistory", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientHistory")
    @ResponseWrapper(localName = "getPatientHistoryResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientHistoryResponse")
    public List<PatientHistory> getPatientHistory(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Allergy>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientAllergies", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientAllergies")
    @ResponseWrapper(localName = "getPatientAllergiesResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientAllergiesResponse")
    public List<Allergy> getPatientAllergies(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Allergy>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDODVLERPatientAllergies", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetDODVLERPatientAllergies")
    @ResponseWrapper(localName = "getDODVLERPatientAllergiesResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetDODVLERPatientAllergiesResponse")
    public List<Allergy> getDODVLERPatientAllergies(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.AllergyDetail
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllergyDetail", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAllergyDetail")
    @ResponseWrapper(localName = "getAllergyDetailResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAllergyDetailResponse")
    public AllergyDetail getAllergyDetail(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientEncountersReport", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientEncountersReport")
    @ResponseWrapper(localName = "getPatientEncountersReportResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientEncountersReportResponse")
    public FreeTextReport getPatientEncountersReport(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.PatientAppointments>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientAppointments", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientAppointments")
    @ResponseWrapper(localName = "getPatientAppointmentsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientAppointmentsResponse")
    public List<PatientAppointments> getPatientAppointments(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Encounter>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientEncounters", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientEncounters")
    @ResponseWrapper(localName = "getPatientEncountersResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientEncountersResponse")
    public List<Encounter> getPatientEncounters(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.ClinicalReminder>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientClinicalReminders", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientClinicalReminders")
    @ResponseWrapper(localName = "getPatientClinicalRemindersResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientClinicalRemindersResponse")
    public List<ClinicalReminder> getPatientClinicalReminders(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClinicalReminderDetail", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetClinicalReminderDetail")
    @ResponseWrapper(localName = "getClinicalReminderDetailResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetClinicalReminderDetailResponse")
    public FreeTextReport getClinicalReminderDetail(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.PatientDemographics>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientDemographics", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientDemographics")
    @ResponseWrapper(localName = "getPatientDemographicsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientDemographicsResponse")
    public List<PatientDemographics> getPatientDemographics(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.PatientDemographicsDetail>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientDemographicsDetail", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientDemographicsDetail")
    @ResponseWrapper(localName = "getPatientDemographicsDetailResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientDemographicsDetailResponse")
    public List<PatientDemographicsDetail> getPatientDemographicsDetail(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Immunization>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientImmunizations", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientImmunizations")
    @ResponseWrapper(localName = "getPatientImmunizationsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientImmunizationsResponse")
    public List<Immunization> getPatientImmunizations(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.LabOrder>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientLabs", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientLabs")
    @ResponseWrapper(localName = "getPatientLabsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientLabsResponse")
    public List<LabOrder> getPatientLabs(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.LabResult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientLabResults", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientLabResults")
    @ResponseWrapper(localName = "getPatientLabResultsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientLabResultsResponse")
    public List<LabResult> getPatientLabResults(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientLabReport", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientLabReport")
    @ResponseWrapper(localName = "getPatientLabReportResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientLabReportResponse")
    public FreeTextReport getPatientLabReport(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Medication>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientMedications", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientMedications")
    @ResponseWrapper(localName = "getPatientMedicationsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientMedicationsResponse")
    public List<Medication> getPatientMedications(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Form>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientForms", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientForms")
    @ResponseWrapper(localName = "getPatientFormsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientFormsResponse")
    public List<Form> getPatientForms(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.ProgressNote>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientProgressNotes", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientProgressNotes")
    @ResponseWrapper(localName = "getPatientProgressNotesResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientProgressNotesResponse")
    public List<ProgressNote> getPatientProgressNotes(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.NoteImage
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBHIENoteImage", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetBHIENoteImage")
    @ResponseWrapper(localName = "getBHIENoteImageResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetBHIENoteImageResponse")
    public NoteImage getBHIENoteImage(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.ProgressNote>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientDischargeSummaries", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientDischargeSummaries")
    @ResponseWrapper(localName = "getPatientDischargeSummariesResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientDischargeSummariesResponse")
    public List<ProgressNote> getPatientDischargeSummaries(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Consult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientConsultRequests", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientConsultRequests")
    @ResponseWrapper(localName = "getPatientConsultRequestsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientConsultRequestsResponse")
    public List<Consult> getPatientConsultRequests(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Order>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientOrders", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientOrders")
    @ResponseWrapper(localName = "getPatientOrdersResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientOrdersResponse")
    public List<Order> getPatientOrders(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Problem>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientProblemList", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientProblemList")
    @ResponseWrapper(localName = "getPatientProblemListResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientProblemListResponse")
    public List<Problem> getPatientProblemList(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.RadiologyReport>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientRads", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientRads")
    @ResponseWrapper(localName = "getPatientRadsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientRadsResponse")
    public List<RadiologyReport> getPatientRads(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Vitals>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientVitals", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientVitals")
    @ResponseWrapper(localName = "getPatientVitalsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientVitalsResponse")
    public List<Vitals> getPatientVitals(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.LabResult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientLabTestResults", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientLabTestResults")
    @ResponseWrapper(localName = "getPatientLabTestResultsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientLabTestResultsResponse")
    public List<LabResult> getPatientLabTestResults(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.LabResult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLabOrderResult", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetLabOrderResult")
    @ResponseWrapper(localName = "getLabOrderResultResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetLabOrderResultResponse")
    public List<LabResult> getLabOrderResult(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.AdmissionDetail
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdmissionDetails", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAdmissionDetails")
    @ResponseWrapper(localName = "getAdmissionDetailsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAdmissionDetailsResponse")
    public AdmissionDetail getAdmissionDetails(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Diagnosis>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdmissionDiagnosis", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAdmissionDiagnosis")
    @ResponseWrapper(localName = "getAdmissionDiagnosisResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAdmissionDiagnosisResponse")
    public List<Diagnosis> getAdmissionDiagnosis(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Procedure>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdmissionProcedures", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAdmissionProcedures")
    @ResponseWrapper(localName = "getAdmissionProceduresResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAdmissionProceduresResponse")
    public List<Procedure> getAdmissionProcedures(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.FreeTextReport>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConsultReport", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetConsultReport")
    @ResponseWrapper(localName = "getConsultReportResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetConsultReportResponse")
    public List<FreeTextReport> getConsultReport(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.User
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderProfile", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderProfile")
    @ResponseWrapper(localName = "getProviderProfileResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderProfileResponse")
    public User getProviderProfile(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMedicationDetail", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetMedicationDetail")
    @ResponseWrapper(localName = "getMedicationDetailResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetMedicationDetailResponse")
    public FreeTextReport getMedicationDetail(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderDetail", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetOrderDetail")
    @ResponseWrapper(localName = "getOrderDetailResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetOrderDetailResponse")
    public FreeTextReport getOrderDetail(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Vitals>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientCurrentVitals", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientCurrentVitals")
    @ResponseWrapper(localName = "getPatientCurrentVitalsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientCurrentVitalsResponse")
    public List<Vitals> getPatientCurrentVitals(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.InsuranceBean>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientInsurances", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientInsurances")
    @ResponseWrapper(localName = "getPatientInsurancesResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetPatientInsurancesResponse")
    public List<InsuranceBean> getPatientInsurances(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Procedure>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOutpatientProcedures", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetOutpatientProcedures")
    @ResponseWrapper(localName = "getOutpatientProceduresResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetOutpatientProceduresResponse")
    public List<Procedure> getOutpatientProcedures(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.ProblemDetail
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProblemDetail", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProblemDetail")
    @ResponseWrapper(localName = "getProblemDetailResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProblemDetailResponse")
    public ProblemDetail getProblemDetail(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProgressNote", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProgressNote")
    @ResponseWrapper(localName = "getProgressNoteResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProgressNoteResponse")
    public FreeTextReport getProgressNote(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.RadiologyReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRadiologyReport", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetRadiologyReport")
    @ResponseWrapper(localName = "getRadiologyReportResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetRadiologyReportResponse")
    public RadiologyReport getRadiologyReport(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.VlerDocument>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVLERDocumentList", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetVLERDocumentList")
    @ResponseWrapper(localName = "getVLERDocumentListResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetVLERDocumentListResponse")
    public List<VlerDocument> getVLERDocumentList(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param vDoc
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.VlerDocument
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVLERDocument", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetVLERDocument")
    @ResponseWrapper(localName = "getVLERDocumentResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetVLERDocumentResponse")
    public VlerDocument getVLERDocument(
            @WebParam(name = "vDoc", targetNamespace = "")
            VlerDocument vDoc,
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Vlerccda>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDODVLERPatientCCDA", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetDODVLERPatientCCDA")
    @ResponseWrapper(localName = "getDODVLERPatientCCDAResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetDODVLERPatientCCDAResponse")
    public List<Vlerccda> getDODVLERPatientCCDA(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Alert>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserAlerts", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetUserAlerts")
    @ResponseWrapper(localName = "getUserAlertsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetUserAlertsResponse")
    public List<Alert> getUserAlerts(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.FreeTextReport
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVisitNotes", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetVisitNotes")
    @ResponseWrapper(localName = "getVisitNotesResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetVisitNotesResponse")
    public FreeTextReport getVisitNotes(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param providerIen
     * @param siteCode
     * @param endDate
     * @param userNPI
     * @param patId
     * @param requestingApp
     * @param userName
     * @param category
     * @param userIen
     * @param startDate
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "logAudit", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.LogAudit")
    @ResponseWrapper(localName = "logAuditResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.LogAuditResponse")
    public void logAudit(
            @WebParam(name = "siteCode", targetNamespace = "")
            String siteCode,
            @WebParam(name = "userIen", targetNamespace = "")
            String userIen,
            @WebParam(name = "providerIen", targetNamespace = "")
            String providerIen,
            @WebParam(name = "userNPI", targetNamespace = "")
            String userNPI,
            @WebParam(name = "userName", targetNamespace = "")
            String userName,
            @WebParam(name = "patId", targetNamespace = "")
            String patId,
            @WebParam(name = "category", targetNamespace = "")
            String category,
            @WebParam(name = "requestingApp", targetNamespace = "")
            String requestingApp,
            @WebParam(name = "startDate", targetNamespace = "")
            String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
            String endDate)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.PatientAppointments>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderAppointments", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderAppointments")
    @ResponseWrapper(localName = "getProviderAppointmentsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderAppointmentsResponse")
    public List<PatientAppointments> getProviderAppointments(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.PatientAdmission>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderAdmissions", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderAdmissions")
    @ResponseWrapper(localName = "getProviderAdmissionsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderAdmissionsResponse")
    public List<PatientAdmission> getProviderAdmissions(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.PatientAdmission>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWardAdmissions", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetWardAdmissions")
    @ResponseWrapper(localName = "getWardAdmissionsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetWardAdmissionsResponse")
    public List<PatientAdmission> getWardAdmissions(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.ProgressNote>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderUnsignedNotes", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderUnsignedNotes")
    @ResponseWrapper(localName = "getProviderUnsignedNotesResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderUnsignedNotesResponse")
    public List<ProgressNote> getProviderUnsignedNotes(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Consult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderConsultsRequested", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderConsultsRequested")
    @ResponseWrapper(localName = "getProviderConsultsRequestedResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderConsultsRequestedResponse")
    public List<Consult> getProviderConsultsRequested(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Consult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderConsultsReceived", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderConsultsReceived")
    @ResponseWrapper(localName = "getProviderConsultsReceivedResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderConsultsReceivedResponse")
    public List<Consult> getProviderConsultsReceived(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Order>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderOrdersPending", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderOrdersPending")
    @ResponseWrapper(localName = "getProviderOrdersPendingResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderOrdersPendingResponse")
    public List<Order> getProviderOrdersPending(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Order>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderOrdersResulted", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderOrdersResulted")
    @ResponseWrapper(localName = "getProviderOrdersResultedResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderOrdersResultedResponse")
    public List<Order> getProviderOrdersResulted(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.LabResult>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderLabAbnormalResults", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderLabAbnormalResults")
    @ResponseWrapper(localName = "getProviderLabAbnormalResultsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderLabAbnormalResultsResponse")
    public List<LabResult> getProviderLabAbnormalResults(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.lang.String
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJanusGUIConfig", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetJanusGUIConfig")
    @ResponseWrapper(localName = "getJanusGUIConfigResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetJanusGUIConfigResponse")
    public String getJanusGUIConfig(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param cfg
     * @param queryBean
     * @return
     *     returns boolean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setJanusGUIConfig", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SetJanusGUIConfig")
    @ResponseWrapper(localName = "setJanusGUIConfigResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SetJanusGUIConfigResponse")
    public boolean setJanusGUIConfig(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean,
            @WebParam(name = "cfg", targetNamespace = "")
            String cfg)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param queryBean
     * @return
     *     returns java.lang.String
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProviderFlags", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderFlags")
    @ResponseWrapper(localName = "getProviderFlagsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetProviderFlagsResponse")
    public String getProviderFlags(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param flags
     * @param queryBean
     * @return
     *     returns boolean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setProviderFlags", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SetProviderFlags")
    @ResponseWrapper(localName = "setProviderFlagsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SetProviderFlagsResponse")
    public boolean setProviderFlags(
            @WebParam(name = "queryBean", targetNamespace = "")
            JMeadowsQuery queryBean,
            @WebParam(name = "flags", targetNamespace = "")
            String flags)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param smartCardID
     * @param smartCardAgency
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.IehrUserProfile
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIehrUserProfile", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetIehrUserProfile")
    @ResponseWrapper(localName = "getIehrUserProfileResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetIehrUserProfileResponse")
    public IehrUserProfile getIehrUserProfile(
            @WebParam(name = "smartCardID", targetNamespace = "")
            String smartCardID,
            @WebParam(name = "smartCardAgency", targetNamespace = "")
            String smartCardAgency)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @param iehrUserProfile
     * @return
     *     returns boolean
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setIehrUserProfile", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SetIehrUserProfile")
    @ResponseWrapper(localName = "setIehrUserProfileResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.SetIehrUserProfileResponse")
    public boolean setIehrUserProfile(
            @WebParam(name = "iehrUserProfile", targetNamespace = "")
            IehrUserProfile iehrUserProfile)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Site>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSites", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetSites")
    @ResponseWrapper(localName = "getSitesResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetSitesResponse")
    public List<Site> getSites();

    /**
     * 
     * @param cardID
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.AuditEntry>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoginInfo", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetLoginInfo")
    @ResponseWrapper(localName = "getLoginInfoResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetLoginInfoResponse")
    public List<AuditEntry> getLoginInfo(
            @WebParam(name = "cardID", targetNamespace = "")
            String cardID)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceErrors", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetServiceErrors")
    @ResponseWrapper(localName = "getServiceErrorsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetServiceErrorsResponse")
    public String getServiceErrors();

    /**
     * 
     * @param authUserInfoQuery
     * @return
     *     returns gov.va.med.jmeadows_2_3_1.webservice.AuthUserInfo
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthUser", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAuthUser")
    @ResponseWrapper(localName = "getAuthUserResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetAuthUserResponse")
    public AuthUserInfo getAuthUser(
            @WebParam(name = "authUserInfoQuery", targetNamespace = "")
            AuthUserInfo authUserInfoQuery)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "resetStatus", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.ResetStatus")
    @ResponseWrapper(localName = "resetStatusResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.ResetStatusResponse")
    public void resetStatus();

    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<gov.va.med.jmeadows_2_3_1.webservice.Patient>
     * @throws JMeadowsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecentlyViewedPatients", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetRecentlyViewedPatients")
    @ResponseWrapper(localName = "getRecentlyViewedPatientsResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetRecentlyViewedPatientsResponse")
    public List<Patient> getRecentlyViewedPatients(
            @WebParam(name = "userId", targetNamespace = "")
            String userId)
        throws JMeadowsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://webservice.jmeadows.domain.ext/", className = "gov.va.med.jmeadows_2_3_1.webservice.GetStatusResponse")
    public String getStatus();

}
