package vistacore.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Activity implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String deploymentId;
   private java.lang.String processDefinitionId;
   private java.lang.String type;
   private java.lang.String domain;
   private java.lang.String processInstanceId;
   private java.lang.String instanceName;
   private java.lang.String patientUid;
   private java.lang.String clinicalObjectUid;
   private java.lang.String sourceFacilityId;
   private java.lang.String destinationFacilityId;
   private java.lang.String state;
   private java.lang.String initiator;
   private java.lang.String timeStamp;
   private java.lang.Integer urgency;
   private java.lang.String assignedTo;
   private java.lang.Boolean activityHealthy;
   private java.lang.String activityHealthDescription;

   public Activity()
   {
   }

   public java.lang.String getDeploymentId()
   {
      return this.deploymentId;
   }

   public void setDeploymentId(java.lang.String deploymentId)
   {
      this.deploymentId = deploymentId;
   }

   public java.lang.String getProcessDefinitionId()
   {
      return this.processDefinitionId;
   }

   public void setProcessDefinitionId(java.lang.String processDefinitionId)
   {
      this.processDefinitionId = processDefinitionId;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getDomain()
   {
      return this.domain;
   }

   public void setDomain(java.lang.String domain)
   {
      this.domain = domain;
   }

   public java.lang.String getProcessInstanceId()
   {
      return this.processInstanceId;
   }

   public void setProcessInstanceId(java.lang.String processInstanceId)
   {
      this.processInstanceId = processInstanceId;
   }

   public java.lang.String getInstanceName()
   {
      return this.instanceName;
   }

   public void setInstanceName(java.lang.String instanceName)
   {
      this.instanceName = instanceName;
   }

   public java.lang.String getPatientUid()
   {
      return this.patientUid;
   }

   public void setPatientUid(java.lang.String patientUid)
   {
      this.patientUid = patientUid;
   }

   public java.lang.String getClinicalObjectUid()
   {
      return this.clinicalObjectUid;
   }

   public void setClinicalObjectUid(java.lang.String clinicalObjectUid)
   {
      this.clinicalObjectUid = clinicalObjectUid;
   }

   public java.lang.String getSourceFacilityId()
   {
      return this.sourceFacilityId;
   }

   public void setSourceFacilityId(java.lang.String sourceFacilityId)
   {
      this.sourceFacilityId = sourceFacilityId;
   }

   public java.lang.String getDestinationFacilityId()
   {
      return this.destinationFacilityId;
   }

   public void setDestinationFacilityId(java.lang.String destinationFacilityId)
   {
      this.destinationFacilityId = destinationFacilityId;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.String getInitiator()
   {
      return this.initiator;
   }

   public void setInitiator(java.lang.String initiator)
   {
      this.initiator = initiator;
   }

   public java.lang.String getTimeStamp()
   {
      return this.timeStamp;
   }

   public void setTimeStamp(java.lang.String timeStamp)
   {
      this.timeStamp = timeStamp;
   }

   public java.lang.Integer getUrgency()
   {
      return this.urgency;
   }

   public void setUrgency(java.lang.Integer urgency)
   {
      this.urgency = urgency;
   }

   public java.lang.String getAssignedTo()
   {
      return this.assignedTo;
   }

   public void setAssignedTo(java.lang.String assignedTo)
   {
      this.assignedTo = assignedTo;
   }

   public java.lang.Boolean getActivityHealthy()
   {
      return this.activityHealthy;
   }

   public void setActivityHealthy(java.lang.Boolean activityHealthy)
   {
      this.activityHealthy = activityHealthy;
   }

   public java.lang.String getActivityHealthDescription()
   {
      return this.activityHealthDescription;
   }

   public void setActivityHealthDescription(
         java.lang.String activityHealthDescription)
   {
      this.activityHealthDescription = activityHealthDescription;
   }

   public Activity(java.lang.String deploymentId,
         java.lang.String processDefinitionId, java.lang.String type,
         java.lang.String domain, java.lang.String processInstanceId,
         java.lang.String instanceName, java.lang.String patientUid,
         java.lang.String clinicalObjectUid, java.lang.String sourceFacilityId,
         java.lang.String destinationFacilityId, java.lang.String state,
         java.lang.String initiator, java.lang.String timeStamp,
         java.lang.Integer urgency, java.lang.String assignedTo,
         java.lang.Boolean activityHealthy,
         java.lang.String activityHealthDescription)
   {
      this.deploymentId = deploymentId;
      this.processDefinitionId = processDefinitionId;
      this.type = type;
      this.domain = domain;
      this.processInstanceId = processInstanceId;
      this.instanceName = instanceName;
      this.patientUid = patientUid;
      this.clinicalObjectUid = clinicalObjectUid;
      this.sourceFacilityId = sourceFacilityId;
      this.destinationFacilityId = destinationFacilityId;
      this.state = state;
      this.initiator = initiator;
      this.timeStamp = timeStamp;
      this.urgency = urgency;
      this.assignedTo = assignedTo;
      this.activityHealthy = activityHealthy;
      this.activityHealthDescription = activityHealthDescription;
   }

}