package vistacore.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AppointmentStatus implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.String name;

   public AppointmentStatus()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public AppointmentStatus(java.lang.String id, java.lang.String name)
   {
      this.id = id;
      this.name = name;
   }

}