package vistacore.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Completion implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String actionText;
   private java.lang.String noteClinicalObjectUid;
   private java.lang.String comment;
   private java.lang.String executionUserId;
   private java.lang.String executionUserName;
   private java.lang.String executionDateTime;
   private vistacore.order.Visit visit;

   private java.lang.String actionId;

   private java.lang.String noteTitle;

   public Completion()
   {
   }

   public java.lang.String getNoteClinicalObjectUid()
   {
      return this.noteClinicalObjectUid;
   }

   public void setNoteClinicalObjectUid(java.lang.String noteClinicalObjectUid)
   {
      this.noteClinicalObjectUid = noteClinicalObjectUid;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public java.lang.String getExecutionDateTime()
   {
      return this.executionDateTime;
   }

   public void setExecutionDateTime(java.lang.String executionDateTime)
   {
      this.executionDateTime = executionDateTime;
   }

   public vistacore.order.Visit getVisit()
   {
      return this.visit;
   }

   public void setVisit(vistacore.order.Visit visit)
   {
      this.visit = visit;
   }

   public java.lang.String getActionText()
   {
      return this.actionText;
   }

   public void setActionText(java.lang.String actionText)
   {
      this.actionText = actionText;
   }

   public java.lang.String getActionId()
   {
      return this.actionId;
   }

   public void setActionId(java.lang.String actionId)
   {
      this.actionId = actionId;
   }

   public java.lang.String getNoteTitle()
   {
      return this.noteTitle;
   }

   public void setNoteTitle(java.lang.String noteTitle)
   {
      this.noteTitle = noteTitle;
   }

   public Completion(java.lang.String actionText,
         java.lang.String noteClinicalObjectUid, java.lang.String comment,
         java.lang.String executionUserId, java.lang.String executionUserName,
         java.lang.String executionDateTime, vistacore.order.Visit visit,
         java.lang.String actionId, java.lang.String noteTitle)
   {
      this.actionText = actionText;
      this.noteClinicalObjectUid = noteClinicalObjectUid;
      this.comment = comment;
      this.executionUserId = executionUserId;
      this.executionUserName = executionUserName;
      this.executionDateTime = executionDateTime;
      this.visit = visit;
      this.actionId = actionId;
      this.noteTitle = noteTitle;
   }

}