package vistacore.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConsultOrderHistory implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   private java.lang.String userId;
   private java.lang.String actionDate;
   private java.lang.String actionComment;

   public ConsultOrderHistory()
   {
   }

   public java.lang.String getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.String userId)
   {
      this.userId = userId;
   }

   public java.lang.String getActionDate()
   {
      return this.actionDate;
   }

   public void setActionDate(java.lang.String actionDate)
   {
      this.actionDate = actionDate;
   }

   public java.lang.String getActionComment()
   {
      return this.actionComment;
   }

   public void setActionComment(java.lang.String actionComment)
   {
      this.actionComment = actionComment;
   }

   public ConsultOrderHistory(java.lang.String userId,
         java.lang.String actionDate, java.lang.String actionComment)
   {
      this.userId = userId;
      this.actionDate = actionDate;
      this.actionComment = actionComment;
   }
}