package vistacore.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConsultOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String condition;

   private java.lang.String urgency;

   private java.lang.String earliestDate;

   private java.lang.String latestDate;

   private java.lang.String location;

   private java.lang.String requestReason;

   private java.util.List<vistacore.order.ConsultOrderHistory> history;

   private java.lang.String attention;

   private java.lang.String scheduledDate;

   private java.lang.String clinic;

   private java.lang.String specialtyProvider;

   private java.lang.String orderingProviderId;

   private java.lang.String contactAttempt;

   private java.lang.String formComment;

   private java.lang.String specialty;

   private java.lang.String orderState;

   private java.lang.String requestComment;

   private java.lang.String requestQuestion;

   private java.lang.String notePreview;

   private java.lang.String noteCondition;

   private java.lang.String noteAnnotation;

   public ConsultOrder()
   {
   }

   public java.lang.String getCondition()
   {
      return this.condition;
   }

   public void setCondition(java.lang.String condition)
   {
      this.condition = condition;
   }

   public java.lang.String getUrgency()
   {
      return this.urgency;
   }

   public void setUrgency(java.lang.String urgency)
   {
      this.urgency = urgency;
   }

   public java.lang.String getEarliestDate()
   {
      return this.earliestDate;
   }

   public void setEarliestDate(java.lang.String earliestDate)
   {
      this.earliestDate = earliestDate;
   }

   public java.lang.String getLatestDate()
   {
      return this.latestDate;
   }

   public void setLatestDate(java.lang.String latestDate)
   {
      this.latestDate = latestDate;
   }

   public java.lang.String getLocation()
   {
      return this.location;
   }

   public void setLocation(java.lang.String location)
   {
      this.location = location;
   }

   public java.lang.String getRequestReason()
   {
      return this.requestReason;
   }

   public void setRequestReason(java.lang.String requestReason)
   {
      this.requestReason = requestReason;
   }

   public java.util.List<vistacore.order.ConsultOrderHistory> getHistory()
   {
      return this.history;
   }

   public void setHistory(
         java.util.List<vistacore.order.ConsultOrderHistory> history)
   {
      this.history = history;
   }

   public java.lang.String getAttention()
   {
      return this.attention;
   }

   public void setAttention(java.lang.String attention)
   {
      this.attention = attention;
   }

   public java.lang.String getScheduledDate()
   {
      return this.scheduledDate;
   }

   public void setScheduledDate(java.lang.String scheduledDate)
   {
      this.scheduledDate = scheduledDate;
   }

   public java.lang.String getClinic()
   {
      return this.clinic;
   }

   public void setClinic(java.lang.String clinic)
   {
      this.clinic = clinic;
   }

   public java.lang.String getSpecialtyProvider()
   {
      return this.specialtyProvider;
   }

   public void setSpecialtyProvider(java.lang.String specialtyProvider)
   {
      this.specialtyProvider = specialtyProvider;
   }

   public java.lang.String getOrderingProviderId()
   {
      return this.orderingProviderId;
   }

   public void setOrderingProviderId(java.lang.String orderingProviderId)
   {
      this.orderingProviderId = orderingProviderId;
   }

   public java.lang.String getContactAttempt()
   {
      return this.contactAttempt;
   }

   public void setContactAttempt(java.lang.String contactAttempt)
   {
      this.contactAttempt = contactAttempt;
   }

   public java.lang.String getFormComment()
   {
      return this.formComment;
   }

   public void setFormComment(java.lang.String formComment)
   {
      this.formComment = formComment;
   }

   public java.lang.String getSpecialty()
   {
      return this.specialty;
   }

   public void setSpecialty(java.lang.String specialty)
   {
      this.specialty = specialty;
   }

   public java.lang.String getOrderState()
   {
      return this.orderState;
   }

   public void setOrderState(java.lang.String orderState)
   {
      this.orderState = orderState;
   }

   public java.lang.String getRequestComment()
   {
      return this.requestComment;
   }

   public void setRequestComment(java.lang.String requestComment)
   {
      this.requestComment = requestComment;
   }

   public java.lang.String getRequestQuestion()
   {
      return this.requestQuestion;
   }

   public void setRequestQuestion(java.lang.String requestQuestion)
   {
      this.requestQuestion = requestQuestion;
   }

   public java.lang.String getNotePreview()
   {
      return this.notePreview;
   }

   public void setNotePreview(java.lang.String notePreview)
   {
      this.notePreview = notePreview;
   }

   public java.lang.String getNoteCondition()
   {
      return this.noteCondition;
   }

   public void setNoteCondition(java.lang.String noteCondition)
   {
      this.noteCondition = noteCondition;
   }

   public java.lang.String getNoteAnnotation()
   {
      return this.noteAnnotation;
   }

   public void setNoteAnnotation(java.lang.String noteAnnotation)
   {
      this.noteAnnotation = noteAnnotation;
   }

   public ConsultOrder(java.lang.String condition, java.lang.String urgency,
         java.lang.String earliestDate, java.lang.String latestDate,
         java.lang.String location, java.lang.String requestReason,
         java.util.List<vistacore.order.ConsultOrderHistory> history,
         java.lang.String attention, java.lang.String scheduledDate,
         java.lang.String clinic, java.lang.String specialtyProvider,
         java.lang.String orderingProviderId, java.lang.String contactAttempt,
         java.lang.String formComment, java.lang.String specialty,
         java.lang.String orderState, java.lang.String requestComment,
         java.lang.String requestQuestion, java.lang.String notePreview,
         java.lang.String noteCondition, java.lang.String noteAnnotation)
   {
      this.condition = condition;
      this.urgency = urgency;
      this.earliestDate = earliestDate;
      this.latestDate = latestDate;
      this.location = location;
      this.requestReason = requestReason;
      this.history = history;
      this.attention = attention;
      this.scheduledDate = scheduledDate;
      this.clinic = clinic;
      this.specialtyProvider = specialtyProvider;
      this.orderingProviderId = orderingProviderId;
      this.contactAttempt = contactAttempt;
      this.formComment = formComment;
      this.specialty = specialty;
      this.orderState = orderState;
      this.requestComment = requestComment;
      this.requestQuestion = requestQuestion;
      this.notePreview = notePreview;
      this.noteCondition = noteCondition;
      this.noteAnnotation = noteAnnotation;
   }

}