package vistacore.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String orderName;
   private java.lang.String orderDate;
   private java.lang.Boolean flag;
   private java.lang.String status;
   private vistacore.order.Provider provider;
   private java.lang.String type;
   private java.lang.String startDate;
   private java.lang.String stopDate;
   private vistacore.order.Facility facility;

   public Order()
   {
   }

   public java.lang.String getOrderName()
   {
      return this.orderName;
   }

   public void setOrderName(java.lang.String orderName)
   {
      this.orderName = orderName;
   }

   public java.lang.String getOrderDate()
   {
      return this.orderDate;
   }

   public void setOrderDate(java.lang.String orderDate)
   {
      this.orderDate = orderDate;
   }

   public java.lang.Boolean getFlag()
   {
      return this.flag;
   }

   public void setFlag(java.lang.Boolean flag)
   {
      this.flag = flag;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public vistacore.order.Provider getProvider()
   {
      return this.provider;
   }

   public void setProvider(vistacore.order.Provider provider)
   {
      this.provider = provider;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getStartDate()
   {
      return this.startDate;
   }

   public void setStartDate(java.lang.String startDate)
   {
      this.startDate = startDate;
   }

   public java.lang.String getStopDate()
   {
      return this.stopDate;
   }

   public void setStopDate(java.lang.String stopDate)
   {
      this.stopDate = stopDate;
   }

   public vistacore.order.Facility getFacility()
   {
      return this.facility;
   }

   public void setFacility(vistacore.order.Facility facility)
   {
      this.facility = facility;
   }

   public Order(java.lang.String orderName, java.lang.String orderDate,
         java.lang.Boolean flag, java.lang.String status,
         vistacore.order.Provider provider, java.lang.String type,
         java.lang.String startDate, java.lang.String stopDate,
         vistacore.order.Facility facility)
   {
      this.orderName = orderName;
      this.orderDate = orderDate;
      this.flag = flag;
      this.status = status;
      this.provider = provider;
      this.type = type;
      this.startDate = startDate;
      this.stopDate = stopDate;
      this.facility = facility;
   }

}