package vistacore.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String assignedFacility;
   private java.lang.String assignedPerson;

   public Person()
   {
   }

   public java.lang.String getAssignedFacility()
   {
      return this.assignedFacility;
   }

   public void setAssignedFacility(java.lang.String assignedFacility)
   {
      this.assignedFacility = assignedFacility;
   }

   public java.lang.String getAssignedPerson()
   {
      return this.assignedPerson;
   }

   public void setAssignedPerson(java.lang.String assignedPerson)
   {
      this.assignedPerson = assignedPerson;
   }

   public Person(java.lang.String assignedFacility, java.lang.String assignedPerson)
   {
      this.assignedFacility = assignedFacility;
      this.assignedPerson = assignedPerson;
   }

}