package vistacore.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Provider implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String uid;
   private java.lang.String displayName;

   public Provider()
   {
   }

   public java.lang.String getUid()
   {
      return this.uid;
   }

   public void setUid(java.lang.String uid)
   {
      this.uid = uid;
   }

   public java.lang.String getDisplayName()
   {
      return this.displayName;
   }

   public void setDisplayName(java.lang.String displayName)
   {
      this.displayName = displayName;
   }

   public Provider(java.lang.String uid, java.lang.String displayName)
   {
      this.uid = uid;
      this.displayName = displayName;
   }

}