package vistacore.order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Visit implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String location;
   private java.lang.String serviceCategory;
   private java.lang.String dateTime;

   private java.lang.String locationDesc;

   public Visit()
   {
   }

   public java.lang.String getLocation()
   {
      return this.location;
   }

   public void setLocation(java.lang.String location)
   {
      this.location = location;
   }

   public java.lang.String getServiceCategory()
   {
      return this.serviceCategory;
   }

   public void setServiceCategory(java.lang.String serviceCategory)
   {
      this.serviceCategory = serviceCategory;
   }

   public java.lang.String getDateTime()
   {
      return this.dateTime;
   }

   public void setDateTime(java.lang.String dateTime)
   {
      this.dateTime = dateTime;
   }

   public java.lang.String getLocationDesc()
   {
      return this.locationDesc;
   }

   public void setLocationDesc(java.lang.String locationDesc)
   {
      this.locationDesc = locationDesc;
   }

   public Visit(java.lang.String location, java.lang.String serviceCategory,
         java.lang.String dateTime, java.lang.String locationDesc)
   {
      this.location = location;
      this.serviceCategory = serviceCategory;
      this.dateTime = dateTime;
      this.locationDesc = locationDesc;
   }

}