require File.dirname(__FILE__) + '/PatientSynchronizer.rb'
require File.dirname(__FILE__) + '/knife-helper.rb'

task :syncCache, [:testType] do |t, args|
  testType = args[:testType]
  if testType == "Acc"
    patient_sync_list = [
      "SITE;100022",
      "SITE;3"
    ]
  else
    patient_sync_list = [
      "SITE;227",
      "SITE;237",
      "SITE;100599",
      "SITE;100840",
      "SITE;271",
      "SITE;301",
      "SITE;8",
      "SITE;231",
      "SITE;100296",
      "SITE;100022",
      "SITE;711",
      "SITE;100023",
      "4325679V4325679",
      "DOD;4325678",
      "SITE;100726",
      "SITE;65",
      "SITE;100319",
      "SITE;253",
      "SITE;3",
      "SITE;631",
      "SITE;229",
      "SITE;100599",
      "SITE;1",
      "SITE;239",
      "SITE;100716",
      "SITE;9",
      "SITE;722",
      "SITE;100731",
      "SITE;100012",
      "SITE;149",
      "SITE;100826",
      "SITE;100470",
      "SITE;100472",
      "SITE;100861",
      "SITE;35",
      "SITE;17",
      "SITE;140",
      "SITE;236"
    ]
  end
  begin
    ENV["JDS_IP"] = knife_search_for_ip("jds")
  rescue
    ENV["JDS_IP"] = knife_search_for_ip("jds_app_server")
  end
  ENV["VX_SYNC_IP"] = knife_search_for_ip("primary_vxsync_client")
  PatientSynchronizer.wait_until_operational_data_loaded "http://#{ENV["JDS_IP"]}:PORT", 1200, ["SITE", "SITE"]
  PatientSynchronizer.synchronize_patient_list "http://#{ENV["VX_SYNC_IP"]}:8080", 3600, patient_sync_list
end
