require File.dirname(__FILE__) + '/PatientSynchronizer.rb'
require File.dirname(__FILE__) + '/knife-helper.rb'

task :syncCache, [:testType] do |t, args|
  testType = args[:testType]
  if testType == "Acc"
    patient_sync_list = [
      "9E7A;100022",
      "9E7A;3"
    ]
  else
    patient_sync_list = [
      "9E7A;227",
      "9E7A;237",
      "9E7A;100599",
      "9E7A;100840",
      "9E7A;271",
      "9E7A;301",
      "9E7A;8",
      "9E7A;164",
      "9E7A;231",
      "9E7A;100296",
      "9E7A;100022",
      "9E7A;711",
      "9E7A;100023",
      "4325679V4325679",
      "DOD;4325678",
      "9E7A;100726",
      "9E7A;65",
      "C877;100319",
      "9E7A;253",
      "9E7A;3",
      "9E7A;631",
      "9E7A;229",
      "C877;100599",
      "9E7A;1",
      "C877;287",
      "9E7A;287",
      "9E7A;239",
      "9E7A;100716",
      "9E7A;9",
      "9E7A;722",
      "9E7A;100731",
      "9E7A;100012",
      "9E7A;149",
      "9E7A;100826",
      "9E7A;100470",
      "9E7A;100472",
      "9E7A;100861",
      "9E7A;35",
      "9E7A;17",
      "9E7A;140"
    ]
  end
  ENV["JDS_IP"] = knife_search_for_ip("jds")
  ENV["VX_SYNC_IP"] = knife_search_for_ip("vxsync_client")
  PatientSynchronizer.wait_until_operational_data_loaded "http://#{ENV["JDS_IP"]}:9080", 1200, ["9E7A", "C877"]
  PatientSynchronizer.synchronize_patient_list "http://#{ENV["VX_SYNC_IP"]}:8080", 3600, patient_sync_list
end
