/*
  This package has only one rule that checks whether a fact is a fhir resource and flags it with Output extension.
  It's purpose is to verify a successful handshake with the CDS engine is done.
*/
package fhirBounceback;
 
import ca.uhn.fhir.model.api.ExtensionDt;
import ca.uhn.fhir.model.primitive.CodeDt;
import ca.uhn.fhir.model.primitive.StringDt;
import ca.uhn.fhir.model.dstu2.resource.BaseResource;
import java.util.List;

import function org.opencds.service.evaluate.FhirUtils.createOutputExtension;

global java.lang.String clientLanguage;
global java.lang.String clientTimeZoneOffset;
global java.lang.String focalPersonId;
global java.util.Date evalTime;
global java.util.HashSet assertions;
global java.util.HashMap namedObjects;

 
rule "FHIR Resource Bounce Back Rule"
     when 
     	 $fhir  : BaseResource()
     then
	 $fhir.addUndeclaredExtension(createOutputExtension()); 
	 //namedObjects.put("fhir", $fhir);  no need to add it becasue opencds has access to the input facts.
end
