define([
    'app/screens/OrdersFull'
], function(OrdersFull) {
    'use strict';
    var detailAppletChannels = {
        "med": "medication_review",
        "document": "documents"
    };
    var config = {
        id: 'discharge-follow-up',
        context: 'patient',
        contentRegionLayout: 'gridster',
        appletHeader: 'navigation',
        appLeft: 'patientInfo',
        predefined: true,
        freezeApplets: true,
        "applets": [{
            "id": "documents",
            "title": "Documents",
            "context": ["patient"],
            "maximizeScreen": "documents-list",
            "showInUDWSelection": true,
            "permissions": ["read-document"],
            "instanceId": "applet-1",
            "region": "applet-1",
            "dataRow": "1",
            "dataCol": "1",
            "dataSizeX": "4",
            "dataSizeY": "6",
            "dataMinSizeX": "4",
            "dataMinSizeY": "4",
            "dataMaxSizeX": "8",
            "dataMaxSizeY": "12",
            "viewType": "summary",
            "filterName": "Discharge Care Coordination",
            "predefinedFilter": true
        }, {
            "id": "orders",
            "title": "Orders",
            "context": ["patient"],
            "maximizeScreen": "orders-full",
            "showInUDWSelection": true,
            "permissions": ["read-order"],
            "instanceId": "applet-2",
            "region": "applet-2",
            "dataRow": "1",
            "dataCol": "5",
            "dataSizeX": "8",
            "dataSizeY": "6",
            "dataMinSizeX": "8",
            "dataMinSizeY": "4",
            "dataMaxSizeX": "12",
            "dataMaxSizeY": "12",
            "viewType": "expanded",
            "filterName": ""
        }, {
            "id": "activeMeds",
            "title": "Active & Recent Medications",
            "context": ["patient"],
            "maximizeScreen": "medication-review",
            "showInUDWSelection": true,
            "permissions": ["read-active-medication"],
            "crsDomain": "Medication",
            "instanceId": "applet-3",
            "region": "applet-3",
            "dataRow": "7",
            "dataCol": "1",
            "dataSizeX": "4",
            "dataSizeY": "6",
            "dataMinSizeX": "4",
            "dataMinSizeY": "4",
            "dataMaxSizeX": "8",
            "dataMaxSizeY": "12",
            "viewType": "gist",
            "filterName": ""
        }, {
            "id": "narrative_lab_results_grid",
            "title": "Narrative Lab Results",
            "context": ["patient"],
            "maximizeScreen": "narrative-lab-results-grid-full",
            "showInUDWSelection": true,
            "permissions": ["read-order"],
            "instanceId": "applet-4",
            "region": "applet-4",
            "dataRow": "7",
            "dataCol": "9",
            "dataSizeX": "4",
            "dataSizeY": "6",
            "dataMinSizeX": "4",
            "dataMinSizeY": "4",
            "dataMaxSizeX": "8",
            "dataMaxSizeY": "12",
            "viewType": "summary",
            "filterName": ""
        }, {
            "id": "lab_results_grid",
            "title": "Numeric Lab Results",
            "context": ["patient"],
            "maximizeScreen": "lab-results-grid-full",
            "showInUDWSelection": true,
            "permissions": ["read-order"],
            "crsDomain": "Laboratory",
            "instanceId": "applet-5",
            "region": "applet-5",
            "dataRow": "7",
            "dataCol": "5",
            "dataSizeX": "4",
            "dataSizeY": "6",
            "dataMinSizeX": "4",
            "dataMinSizeY": "3",
            "dataMaxSizeX": "8",
            "dataMaxSizeY": "12",
            "viewType": "gist",
            "filterName": ""
        }, {
            "id": "appointments",
            "title": "Appointments & Visits",
            "context": ["patient"],
            "maximizeScreen": "appointments-full",
            "showInUDWSelection": true,
            "permissions": ["read-encounter"],
            "instanceId": "applet-6",
            "region": "applet-6",
            "dataRow": "7",
            "dataCol": "13",
            "dataSizeX": "4",
            "dataSizeY": "6",
            "dataMinSizeX": "4",
            "dataMinSizeY": "4",
            "dataMaxSizeX": "8",
            "dataMaxSizeY": "12",
            "viewType": "summary",
            "filterName": ""
        }, {
            "id": "problems",
            "title": "Problems",
            "context": ["patient"],
            "maximizeScreen": "problems-full",
            "showInUDWSelection": true,
            "permissions": ["read-condition-problem"],
            "crsDomain": "Problem",
            "instanceId": "applet-7",
            "region": "applet-7",
            "dataRow": "1",
            "dataCol": "13",
            "dataSizeX": "4",
            "dataSizeY": "6",
            "dataMinSizeX": "4",
            "dataMinSizeY": "3",
            "dataMaxSizeX": "8",
            "dataMaxSizeY": "12",
            "viewType": "summary",
            "filterName": ""
        }],
        onStart: function() {
            OrdersFull.setUpEvents();
        },
        onStop: function() {
            OrdersFull.turnOffEvents();
        },
        patientRequired: true
    };
    return config;
});