package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CdsIntentResult implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private vistacore.order.consult.CdsIntentData data;
   private java.lang.Integer status;

   public CdsIntentResult()
   {
   }

   public vistacore.order.consult.CdsIntentData getData()
   {
      return this.data;
   }

   public void setData(vistacore.order.consult.CdsIntentData data)
   {
      this.data = data;
   }

   public java.lang.Integer getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.Integer status)
   {
      this.status = status;
   }

   public CdsIntentResult(vistacore.order.consult.CdsIntentData data,
         java.lang.Integer status)
   {
      this.data = data;
      this.status = status;
   }

}