package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Code implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String code;
   private java.lang.String display;
   private java.lang.String system;

   public Code()
   {
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.lang.String getDisplay()
   {
      return this.display;
   }

   public void setDisplay(java.lang.String display)
   {
      this.display = display;
   }

   public java.lang.String getSystem()
   {
      return this.system;
   }

   public void setSystem(java.lang.String system)
   {
      this.system = system;
   }

   public Code(java.lang.String code, java.lang.String display,
         java.lang.String system)
   {
      this.code = code;
      this.display = display;
      this.system = system;
   }

}