package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConsultClinicalObjectData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private vistacore.order.Activity activity;
   private java.util.List<vistacore.order.consult.Signal> signals;
   private vistacore.order.Order order;
   private java.util.List<vistacore.order.consult.Triage> triages;
   private java.util.List<vistacore.order.consult.Schedule> schedules;
   private java.util.List<vistacore.order.Appointment> appointments;
   private vistacore.order.Completion completion;

   private java.util.List<vistacore.order.consult.Sign> signs;

   private Review review;

   private java.util.List<vistacore.order.consult.Milestone> milestones;

   private java.util.List<vistacore.order.consult.ConsultOrderData> consultOrders;

   public ConsultClinicalObjectData()
   {
   }

   public vistacore.order.Activity getActivity()
   {
      return this.activity;
   }

   public void setActivity(vistacore.order.Activity activity)
   {
      this.activity = activity;
   }

   public java.util.List<vistacore.order.consult.Signal> getSignals()
   {
      return this.signals;
   }

   public void setSignals(
         java.util.List<vistacore.order.consult.Signal> signals)
   {
      this.signals = signals;
   }

   public vistacore.order.Order getOrder()
   {
      return this.order;
   }

   public void setOrder(vistacore.order.Order order)
   {
      this.order = order;
   }

   public java.util.List<vistacore.order.consult.Triage> getTriages()
   {
      return this.triages;
   }

   public void setTriages(
         java.util.List<vistacore.order.consult.Triage> triages)
   {
      this.triages = triages;
   }

   public java.util.List<vistacore.order.consult.Schedule> getSchedules()
   {
      return this.schedules;
   }

   public void setSchedules(
         java.util.List<vistacore.order.consult.Schedule> schedules)
   {
      this.schedules = schedules;
   }

   public java.util.List<vistacore.order.Appointment> getAppointments()
   {
      return this.appointments;
   }

   public void setAppointments(
         java.util.List<vistacore.order.Appointment> appointments)
   {
      this.appointments = appointments;
   }

   public vistacore.order.Completion getCompletion()
   {
      return this.completion;
   }

   public void setCompletion(vistacore.order.Completion completion)
   {
      this.completion = completion;
   }

   public java.util.List<vistacore.order.consult.Sign> getSigns()
   {
      return this.signs;
   }

   public void setSigns(java.util.List<vistacore.order.consult.Sign> signs)
   {
      this.signs = signs;
   }

   public java.util.List<vistacore.order.consult.Milestone> getMilestones()
   {
      return this.milestones;
   }

   public void setMilestones(
         java.util.List<vistacore.order.consult.Milestone> milestones)
   {
      this.milestones = milestones;
   }

   public vistacore.order.consult.Review getReview()
   {
      return this.review;
   }

   public void setReview(vistacore.order.consult.Review review)
   {
      this.review = review;
   }

   public java.util.List<vistacore.order.consult.ConsultOrderData> getConsultOrders()
   {
      return this.consultOrders;
   }

   public void setConsultOrders(
         java.util.List<vistacore.order.consult.ConsultOrderData> consultOrders)
   {
      this.consultOrders = consultOrders;
   }

   public ConsultClinicalObjectData(vistacore.order.Activity activity,
         java.util.List<vistacore.order.consult.Signal> signals,
         vistacore.order.Order order,
         java.util.List<vistacore.order.consult.Triage> triages,
         java.util.List<vistacore.order.consult.Schedule> schedules,
         java.util.List<vistacore.order.Appointment> appointments,
         vistacore.order.Completion completion,
         java.util.List<vistacore.order.consult.Sign> signs,
         vistacore.order.consult.Review review,
         java.util.List<vistacore.order.consult.Milestone> milestones,
         java.util.List<vistacore.order.consult.ConsultOrderData> consultOrders)
   {
      this.activity = activity;
      this.signals = signals;
      this.order = order;
      this.triages = triages;
      this.schedules = schedules;
      this.appointments = appointments;
      this.completion = completion;
      this.signs = signs;
      this.review = review;
      this.milestones = milestones;
      this.consultOrders = consultOrders;
   }

}