package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConsultPreReqOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String orderName;
   private java.lang.String status;
   private java.lang.String statusDate;
   private java.lang.Boolean signalRegistered;

   private java.lang.String uid;

   public ConsultPreReqOrder()
   {
   }

   public java.lang.String getOrderName()
   {
      return this.orderName;
   }

   public void setOrderName(java.lang.String orderName)
   {
      this.orderName = orderName;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getStatusDate()
   {
      return this.statusDate;
   }

   public void setStatusDate(java.lang.String statusDate)
   {
      this.statusDate = statusDate;
   }

   public java.lang.String getUid()
   {
      return this.uid;
   }

   public void setUid(java.lang.String uid)
   {
      this.uid = uid;
   }

   public java.lang.Boolean getSignalRegistered()
   {
      return this.signalRegistered;
   }

   public void setSignalRegistered(java.lang.Boolean signalRegistered)
   {
      this.signalRegistered = signalRegistered;
   }

   public ConsultPreReqOrder(java.lang.String orderName, java.lang.String status,
         java.lang.String statusDate, java.lang.Boolean signalRegistered,
         java.lang.String uid)
   {
      this.orderName = orderName;
      this.status = status;
      this.statusDate = statusDate;
      this.signalRegistered = signalRegistered;
      this.uid = uid;
   }

}