package vistacore.order.consult;

import vistacore.order.Provider;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.remote.Remotable
public class ConsultOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String urgency;

   private java.lang.String earliestDate;

   private java.lang.String latestDate;

   private java.lang.String requestReason;

   private java.lang.String scheduledDate;

   private Provider acceptingProvider;

   private java.lang.String contactAttempt;

   private java.lang.String formComment;

   private java.lang.String requestComment;

   private java.lang.String overrideReason;

   private java.util.List<vistacore.order.consult.ConsultPreReqQuestion> preReqQuestions;

   private java.util.List<vistacore.order.consult.ConsultPreReqOrder> preReqOrders;

   private java.lang.String formAction;

   private java.lang.String communityCareType;

   private java.lang.String communityCareStatus;

   private java.lang.String consultName;

   private java.lang.String processDefId;

   private java.lang.String deploymentId;

   private java.util.List<vistacore.order.consult.Condition> conditions;

   private vistacore.order.consult.TeamFocus teamFocus;

   private java.lang.String instructions;

   private vistacore.order.Facility orderingFacility;

   private vistacore.order.Provider orderingProvider;

   private vistacore.order.Visit visit;

   private vistacore.order.Facility destinationFacility;

   private vistacore.order.Facility acceptingClinic;

   private java.lang.String executionUserId;

   private java.lang.String executionUserName;

   private java.lang.String orderResultComment;

   public ConsultOrder()
   {
   }

   public java.lang.String getEarliestDate()
   {
      return this.earliestDate;
   }

   public void setEarliestDate(java.lang.String earliestDate)
   {
      this.earliestDate = earliestDate;
   }

   public java.lang.String getLatestDate()
   {
      return this.latestDate;
   }

   public void setLatestDate(java.lang.String latestDate)
   {
      this.latestDate = latestDate;
   }

   public java.lang.String getRequestReason()
   {
      return this.requestReason;
   }

   public void setRequestReason(java.lang.String requestReason)
   {
      this.requestReason = requestReason;
   }

   public java.lang.String getScheduledDate()
   {
      return this.scheduledDate;
   }

   public void setScheduledDate(java.lang.String scheduledDate)
   {
      this.scheduledDate = scheduledDate;
   }

   public java.lang.String getContactAttempt()
   {
      return this.contactAttempt;
   }

   public void setContactAttempt(java.lang.String contactAttempt)
   {
      this.contactAttempt = contactAttempt;
   }

   public java.lang.String getFormComment()
   {
      return this.formComment;
   }

   public void setFormComment(java.lang.String formComment)
   {
      this.formComment = formComment;
   }

   public java.lang.String getRequestComment()
   {
      return this.requestComment;
   }

   public void setRequestComment(java.lang.String requestComment)
   {
      this.requestComment = requestComment;
   }

   public java.lang.String getOverrideReason()
   {
      return this.overrideReason;
   }

   public void setOverrideReason(java.lang.String overrideReason)
   {
      this.overrideReason = overrideReason;
   }

   public java.util.List<vistacore.order.consult.ConsultPreReqQuestion> getPreReqQuestions()
   {
      return this.preReqQuestions;
   }

   public void setPreReqQuestions(
         java.util.List<vistacore.order.consult.ConsultPreReqQuestion> preReqQuestions)
   {
      this.preReqQuestions = preReqQuestions;
   }

   public java.util.List<vistacore.order.consult.ConsultPreReqOrder> getPreReqOrders()
   {
      return this.preReqOrders;
   }

   public void setPreReqOrders(
         java.util.List<vistacore.order.consult.ConsultPreReqOrder> preReqOrders)
   {
      this.preReqOrders = preReqOrders;
   }

   public java.lang.String getFormAction()
   {
      return this.formAction;
   }

   public void setFormAction(java.lang.String formAction)
   {
      this.formAction = formAction;
   }

   public java.lang.String getCommunityCareType()
   {
      return this.communityCareType;
   }

   public void setCommunityCareType(java.lang.String communityCareType)
   {
      this.communityCareType = communityCareType;
   }

   public java.lang.String getCommunityCareStatus()
   {
      return this.communityCareStatus;
   }

   public void setCommunityCareStatus(java.lang.String communityCareStatus)
   {
      this.communityCareStatus = communityCareStatus;
   }

   public java.lang.String getConsultName()
   {
      return this.consultName;
   }

   public void setConsultName(java.lang.String consultName)
   {
      this.consultName = consultName;
   }

   public java.lang.String getProcessDefId()
   {
      return this.processDefId;
   }

   public void setProcessDefId(java.lang.String processDefId)
   {
      this.processDefId = processDefId;
   }

   public java.lang.String getDeploymentId()
   {
      return this.deploymentId;
   }

   public void setDeploymentId(java.lang.String deploymentId)
   {
      this.deploymentId = deploymentId;
   }

   public vistacore.order.Provider getAcceptingProvider()
   {
      return this.acceptingProvider;
   }

   public void setAcceptingProvider(vistacore.order.Provider acceptingProvider)
   {
      this.acceptingProvider = acceptingProvider;
   }

   public java.util.List<vistacore.order.consult.Condition> getConditions()
   {
      return this.conditions;
   }

   public void setConditions(
         java.util.List<vistacore.order.consult.Condition> conditions)
   {
      this.conditions = conditions;
   }

   public vistacore.order.consult.TeamFocus getTeamFocus()
   {
      return this.teamFocus;
   }

   public void setTeamFocus(vistacore.order.consult.TeamFocus teamFocus)
   {
      this.teamFocus = teamFocus;
   }

   public java.lang.String getInstructions()
   {
      return this.instructions;
   }

   public void setInstructions(java.lang.String instructions)
   {
      this.instructions = instructions;
   }

   public vistacore.order.Facility getOrderingFacility()
   {
      return this.orderingFacility;
   }

   public void setOrderingFacility(vistacore.order.Facility orderingFacility)
   {
      this.orderingFacility = orderingFacility;
   }

   public vistacore.order.Provider getOrderingProvider()
   {
      return this.orderingProvider;
   }

   public void setOrderingProvider(vistacore.order.Provider orderingProvider)
   {
      this.orderingProvider = orderingProvider;
   }

   public vistacore.order.Visit getVisit()
   {
      return this.visit;
   }

   public void setVisit(vistacore.order.Visit visit)
   {
      this.visit = visit;
   }

   public java.lang.String getUrgency()
   {
      return this.urgency;
   }

   public void setUrgency(java.lang.String urgency)
   {
      this.urgency = urgency;
   }

   public vistacore.order.Facility getDestinationFacility()
   {
      return this.destinationFacility;
   }

   public void setDestinationFacility(vistacore.order.Facility destinationFacility)
   {
      this.destinationFacility = destinationFacility;
   }

   public vistacore.order.Facility getAcceptingClinic()
   {
      return this.acceptingClinic;
   }

   public void setAcceptingClinic(vistacore.order.Facility acceptingClinic)
   {
      this.acceptingClinic = acceptingClinic;
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public java.lang.String getOrderResultComment()
   {
      return this.orderResultComment;
   }

   public void setOrderResultComment(java.lang.String orderResultComment)
   {
      this.orderResultComment = orderResultComment;
   }

   public ConsultOrder(
         java.lang.String urgency,
         java.lang.String earliestDate,
         java.lang.String latestDate,
         java.lang.String requestReason,
         java.lang.String scheduledDate,
         vistacore.order.Provider acceptingProvider,
         java.lang.String contactAttempt,
         java.lang.String formComment,
         java.lang.String requestComment,
         java.lang.String overrideReason,
         java.util.List<vistacore.order.consult.ConsultPreReqQuestion> preReqQuestions,
         java.util.List<vistacore.order.consult.ConsultPreReqOrder> preReqOrders,
         java.lang.String formAction, java.lang.String communityCareType,
         java.lang.String communityCareStatus, java.lang.String consultName,
         java.lang.String processDefId, java.lang.String deploymentId,
         java.util.List<vistacore.order.consult.Condition> conditions,
         vistacore.order.consult.TeamFocus teamFocus,
         java.lang.String instructions,
         vistacore.order.Facility orderingFacility,
         vistacore.order.Provider orderingProvider, vistacore.order.Visit visit,
         vistacore.order.Facility destinationFacility,
         vistacore.order.Facility acceptingClinic,
         java.lang.String executionUserId, java.lang.String executionUserName,
         java.lang.String orderResultComment)
   {
      this.urgency = urgency;
      this.earliestDate = earliestDate;
      this.latestDate = latestDate;
      this.requestReason = requestReason;
      this.scheduledDate = scheduledDate;
      this.acceptingProvider = acceptingProvider;
      this.contactAttempt = contactAttempt;
      this.formComment = formComment;
      this.requestComment = requestComment;
      this.overrideReason = overrideReason;
      this.preReqQuestions = preReqQuestions;
      this.preReqOrders = preReqOrders;
      this.formAction = formAction;
      this.communityCareType = communityCareType;
      this.communityCareStatus = communityCareStatus;
      this.consultName = consultName;
      this.processDefId = processDefId;
      this.deploymentId = deploymentId;
      this.conditions = conditions;
      this.teamFocus = teamFocus;
      this.instructions = instructions;
      this.orderingFacility = orderingFacility;
      this.orderingProvider = orderingProvider;
      this.visit = visit;
      this.destinationFacility = destinationFacility;
      this.acceptingClinic = acceptingClinic;
      this.executionUserId = executionUserId;
      this.executionUserName = executionUserName;
      this.orderResultComment = orderResultComment;
   }

}