package vistacore.order.consult;

import vistacore.order.Provider;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConsultOrderData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private Integer urgency;

   private java.lang.String earliestDate;

   private java.lang.String latestDate;

   private java.lang.String request;

   private Provider acceptingProvider;

   private java.lang.String comment;

   private java.lang.String overrideReason;

   private java.util.List<vistacore.order.consult.ConsultPreReqQuestion> questions;

   private java.util.List<vistacore.order.consult.ConsultPreReqOrder> orderResults;

   private java.lang.String action;

   private java.lang.String consultName;

   private java.util.List<vistacore.order.consult.Condition> conditions;

   private vistacore.order.Facility facility;

   private vistacore.order.Visit visit;

   private String orderable;
   
   private java.lang.String executionUserId;

   private java.lang.String executionUserName;

   private java.lang.String executionDateTime;
   
   private String cdsIntentResult;

   private java.lang.String orderResultComment;

   public ConsultOrderData()
   {
   }

   public java.lang.String getEarliestDate()
   {
      return this.earliestDate;
   }

   public void setEarliestDate(java.lang.String earliestDate)
   {
      this.earliestDate = earliestDate;
   }

   public java.lang.String getLatestDate()
   {
      return this.latestDate;
   }

   public void setLatestDate(java.lang.String latestDate)
   {
      this.latestDate = latestDate;
   }

   public java.lang.String getOverrideReason()
   {
      return this.overrideReason;
   }

   public void setOverrideReason(java.lang.String overrideReason)
   {
      this.overrideReason = overrideReason;
   }

   public java.lang.String getConsultName()
   {
      return this.consultName;
   }

   public void setConsultName(java.lang.String consultName)
   {
      this.consultName = consultName;
   }

   public vistacore.order.Provider getAcceptingProvider()
   {
      return this.acceptingProvider;
   }

   public void setAcceptingProvider(vistacore.order.Provider acceptingProvider)
   {
      this.acceptingProvider = acceptingProvider;
   }

   public java.util.List<vistacore.order.consult.Condition> getConditions()
   {
      return this.conditions;
   }

   public void setConditions(
         java.util.List<vistacore.order.consult.Condition> conditions)
   {
      this.conditions = conditions;
   }

   public vistacore.order.Visit getVisit()
   {
      return this.visit;
   }

   public void setVisit(vistacore.order.Visit visit)
   {
      this.visit = visit;
   }

   public java.lang.String getAction()
   {
      return this.action;
   }

   public void setAction(java.lang.String action)
   {
      this.action = action;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public java.lang.Integer getUrgency()
   {
      return this.urgency;
   }

   public void setUrgency(java.lang.Integer urgency)
   {
      this.urgency = urgency;
   }

   public vistacore.order.Facility getFacility()
   {
      return this.facility;
   }

   public void setFacility(vistacore.order.Facility facility)
   {
      this.facility = facility;
   }

   public java.lang.String getRequest()
   {
      return this.request;
   }

   public void setRequest(java.lang.String request)
   {
      this.request = request;
   }

   public java.util.List<vistacore.order.consult.ConsultPreReqQuestion> getQuestions()
   {
      return this.questions;
   }

   public void setQuestions(
         java.util.List<vistacore.order.consult.ConsultPreReqQuestion> questions)
   {
      this.questions = questions;
   }

   public java.util.List<vistacore.order.consult.ConsultPreReqOrder> getOrderResults()
   {
      return this.orderResults;
   }

   public void setOrderResults(
         java.util.List<vistacore.order.consult.ConsultPreReqOrder> orderResults)
   {
      this.orderResults = orderResults;
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public java.lang.String getExecutionDateTime()
   {
      return this.executionDateTime;
   }

   public void setExecutionDateTime(java.lang.String executionDateTime)
   {
      this.executionDateTime = executionDateTime;
   }

   public String getCdsIntentResult() {
	   return cdsIntentResult;
   }
	
   public void setCdsIntentResult(String cdsIntentResult) {
	   this.cdsIntentResult = cdsIntentResult;
   }

   public String getOrderable()
   {
      return this.orderable;
   }

   public void setOrderable(String orderable)
   {
      this.orderable = orderable;
   }

   public java.lang.String getOrderResultComment()
   {
      return this.orderResultComment;
   }

   public void setOrderResultComment(java.lang.String orderResultComment)
   {
      this.orderResultComment = orderResultComment;
   }

   public ConsultOrderData(
         java.lang.Integer urgency,
         java.lang.String earliestDate,
         java.lang.String latestDate,
         java.lang.String request,
         vistacore.order.Provider acceptingProvider,
         java.lang.String comment,
         java.lang.String overrideReason,
         java.util.List<vistacore.order.consult.ConsultPreReqQuestion> questions,
         java.util.List<vistacore.order.consult.ConsultPreReqOrder> orderResults,
         java.lang.String action, java.lang.String consultName,
         java.util.List<vistacore.order.consult.Condition> conditions,
         vistacore.order.Facility facility, vistacore.order.Visit visit,
         String orderable,
         java.lang.String executionUserId, java.lang.String executionUserName,
         java.lang.String executionDateTime,
         String cdsIntentResult,
         java.lang.String orderResultComment)
   {
      this.urgency = urgency;
      this.earliestDate = earliestDate;
      this.latestDate = latestDate;
      this.request = request;
      this.acceptingProvider = acceptingProvider;
      this.comment = comment;
      this.overrideReason = overrideReason;
      this.questions = questions;
      this.orderResults = orderResults;
      this.action = action;
      this.consultName = consultName;
      this.conditions = conditions;
      this.facility = facility;
      this.visit = visit;
      this.orderable = orderable;
      this.executionUserId = executionUserId;
      this.executionUserName = executionUserName;
      this.executionDateTime = executionDateTime;
      this.cdsIntentResult = cdsIntentResult;
      this.orderResultComment = orderResultComment;
   }

}
