package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DerivedFrom implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String form;
   private java.lang.String item;
   private vistacore.order.consult.Version version;

   public DerivedFrom()
   {
   }

   public java.lang.String getForm()
   {
      return this.form;
   }

   public void setForm(java.lang.String form)
   {
      this.form = form;
   }

   public java.lang.String getItem()
   {
      return this.item;
   }

   public void setItem(java.lang.String item)
   {
      this.item = item;
   }

   public vistacore.order.consult.Version getVersion()
   {
      return this.version;
   }

   public void setVersion(vistacore.order.consult.Version version)
   {
      this.version = version;
   }

   public DerivedFrom(java.lang.String form, java.lang.String item,
         vistacore.order.consult.Version version)
   {
      this.form = form;
      this.item = item;
      this.version = version;
   }

}