package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Detail implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String resourceType;
   private java.lang.String comments;
   private java.lang.String status;
   private java.util.List<vistacore.order.consult.Identifier> identifier;

   public Detail()
   {
   }

   public java.lang.String getResourceType()
   {
      return this.resourceType;
   }

   public void setResourceType(java.lang.String resourceType)
   {
      this.resourceType = resourceType;
   }

   public java.lang.String getComments()
   {
      return this.comments;
   }

   public void setComments(java.lang.String comments)
   {
      this.comments = comments;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.util.List<vistacore.order.consult.Identifier> getIdentifier()
   {
      return this.identifier;
   }

   public void setIdentifier(
         java.util.List<vistacore.order.consult.Identifier> identifier)
   {
      this.identifier = identifier;
   }

   public Detail(java.lang.String resourceType, java.lang.String comments,
         java.lang.String status,
         java.util.List<vistacore.order.consult.Identifier> identifier)
   {
      this.resourceType = resourceType;
      this.comments = comments;
      this.status = status;
      this.identifier = identifier;
   }

}