package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EhmpQuestionnaire implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<vistacore.order.consult.ObservationResult> observationResults;

   public EhmpQuestionnaire()
   {
   }

   public java.util.List<vistacore.order.consult.ObservationResult> getObservationResults()
   {
      return this.observationResults;
   }

   public void setObservationResults(
         java.util.List<vistacore.order.consult.ObservationResult> observationResults)
   {
      this.observationResults = observationResults;
   }

   public EhmpQuestionnaire(
         java.util.List<vistacore.order.consult.ObservationResult> observationResults)
   {
      this.observationResults = observationResults;
   }

}