package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Identifier implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String system;
   private java.lang.String value;

   public Identifier()
   {
   }

   public java.lang.String getSystem()
   {
      return this.system;
   }

   public void setSystem(java.lang.String system)
   {
      this.system = system;
   }

   public java.lang.String getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }

   public Identifier(java.lang.String system, java.lang.String value)
   {
      this.system = system;
      this.value = value;
   }

}