package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Milestone implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String startDateTime;

   public Milestone()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getStartDateTime()
   {
      return this.startDateTime;
   }

   public void setStartDateTime(java.lang.String startDateTime)
   {
      this.startDateTime = startDateTime;
   }

   public Milestone(java.lang.String name, java.lang.String startDateTime)
   {
      this.name = name;
      this.startDateTime = startDateTime;
   }

}