package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderableData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private vistacore.order.Activity activity;
   private java.util.List<vistacore.order.consult.Code> codes;
   private java.lang.String instructions;
   private vistacore.order.consult.Prerequisites prerequisites;
   private vistacore.order.consult.TeamFocus teamFocus;

   public OrderableData()
   {
   }

   public vistacore.order.Activity getActivity()
   {
      return this.activity;
   }

   public void setActivity(vistacore.order.Activity activity)
   {
      this.activity = activity;
   }

   public java.util.List<vistacore.order.consult.Code> getCodes()
   {
      return this.codes;
   }

   public void setCodes(java.util.List<vistacore.order.consult.Code> codes)
   {
      this.codes = codes;
   }

   public java.lang.String getInstructions()
   {
      return this.instructions;
   }

   public void setInstructions(java.lang.String instructions)
   {
      this.instructions = instructions;
   }

   public vistacore.order.consult.Prerequisites getPrerequisites()
   {
      return this.prerequisites;
   }

   public void setPrerequisites(
         vistacore.order.consult.Prerequisites prerequisites)
   {
      this.prerequisites = prerequisites;
   }

   public vistacore.order.consult.TeamFocus getTeamFocus()
   {
      return this.teamFocus;
   }

   public void setTeamFocus(vistacore.order.consult.TeamFocus teamFocus)
   {
      this.teamFocus = teamFocus;
   }

   public OrderableData(vistacore.order.Activity activity,
         java.util.List<vistacore.order.consult.Code> codes,
         java.lang.String instructions,
         vistacore.order.consult.Prerequisites prerequisites,
         vistacore.order.consult.TeamFocus teamFocus)
   {
      this.activity = activity;
      this.codes = codes;
      this.instructions = instructions;
      this.prerequisites = prerequisites;
      this.teamFocus = teamFocus;
   }

}