package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prerequisites implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String cdsIntent;
   private vistacore.order.consult.EhmpQuestionnaire ehmpQuestionnaire;

   public Prerequisites()
   {
   }

   public java.lang.String getCdsIntent()
   {
      return this.cdsIntent;
   }

   public void setCdsIntent(java.lang.String cdsIntent)
   {
      this.cdsIntent = cdsIntent;
   }

   public vistacore.order.consult.EhmpQuestionnaire getEhmpQuestionnaire()
   {
      return this.ehmpQuestionnaire;
   }

   public void setEhmpQuestionnaire(
         vistacore.order.consult.EhmpQuestionnaire ehmpQuestionnaire)
   {
      this.ehmpQuestionnaire = ehmpQuestionnaire;
   }

   public Prerequisites(java.lang.String cdsIntent,
         vistacore.order.consult.EhmpQuestionnaire ehmpQuestionnaire)
   {
      this.cdsIntent = cdsIntent;
      this.ehmpQuestionnaire = ehmpQuestionnaire;
   }

}