package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Remediation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String action;
   private vistacore.order.consult.Code coding;
   private java.lang.String domain;

   public Remediation()
   {
   }

   public java.lang.String getAction()
   {
      return this.action;
   }

   public void setAction(java.lang.String action)
   {
      this.action = action;
   }

   public vistacore.order.consult.Code getCoding()
   {
      return this.coding;
   }

   public void setCoding(vistacore.order.consult.Code coding)
   {
      this.coding = coding;
   }

   public java.lang.String getDomain()
   {
      return this.domain;
   }

   public void setDomain(java.lang.String domain)
   {
      this.domain = domain;
   }

   public Remediation(java.lang.String action,
         vistacore.order.consult.Code coding, java.lang.String domain)
   {
      this.action = action;
      this.coding = coding;
      this.domain = domain;
   }

}