package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Review implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String executionUserId;

   private java.lang.String executionDateTime;

   private java.lang.String executionUserName;

   public Review()
   {
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionDateTime()
   {
      return this.executionDateTime;
   }

   public void setExecutionDateTime(java.lang.String executionDateTime)
   {
      this.executionDateTime = executionDateTime;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public Review(java.lang.String executionUserId,
         java.lang.String executionDateTime, java.lang.String executionUserName)
   {
      this.executionUserId = executionUserId;
      this.executionDateTime = executionDateTime;
      this.executionUserName = executionUserName;
   }

}