package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Schedule implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String comment;
   private java.lang.String contactAttempt;
   private vistacore.order.Appointment appointment;
   private java.lang.String executionUserId;
   private java.lang.String executionUserName;
   private java.lang.String executionDateTime;

   private java.lang.String actionText;

   private java.lang.String actionId;

   public Schedule()
   {
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public java.lang.String getContactAttempt()
   {
      return this.contactAttempt;
   }

   public void setContactAttempt(java.lang.String contactAttempt)
   {
      this.contactAttempt = contactAttempt;
   }

   public vistacore.order.Appointment getAppointment()
   {
      return this.appointment;
   }

   public void setAppointment(vistacore.order.Appointment appointment)
   {
      this.appointment = appointment;
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public java.lang.String getExecutionDateTime()
   {
      return this.executionDateTime;
   }

   public void setExecutionDateTime(java.lang.String executionDateTime)
   {
      this.executionDateTime = executionDateTime;
   }

   public java.lang.String getActionText()
   {
      return this.actionText;
   }

   public void setActionText(java.lang.String actionText)
   {
      this.actionText = actionText;
   }

   public java.lang.String getActionId()
   {
      return this.actionId;
   }

   public void setActionId(java.lang.String actionId)
   {
      this.actionId = actionId;
   }

   public Schedule(java.lang.String comment, java.lang.String contactAttempt,
         vistacore.order.Appointment appointment,
         java.lang.String executionUserId, java.lang.String executionUserName,
         java.lang.String executionDateTime, java.lang.String actionText,
         java.lang.String actionId)
   {
      this.comment = comment;
      this.contactAttempt = contactAttempt;
      this.appointment = appointment;
      this.executionUserId = executionUserId;
      this.executionUserName = executionUserName;
      this.executionDateTime = executionDateTime;
      this.actionText = actionText;
      this.actionId = actionId;
   }

}