package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Sign implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String comment;
   private java.lang.String executionUserSignatureCode;
   private java.lang.String executionUserId;
   private java.lang.String executionUserName;
   private java.lang.String executionDateTime;
   private vistacore.order.Visit visit;

   public Sign()
   {
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public java.lang.String getExecutionUserSignatureCode()
   {
      return this.executionUserSignatureCode;
   }

   public void setExecutionUserSignatureCode(
         java.lang.String executionUserSignatureCode)
   {
      this.executionUserSignatureCode = executionUserSignatureCode;
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public java.lang.String getExecutionDateTime()
   {
      return this.executionDateTime;
   }

   public void setExecutionDateTime(java.lang.String executionDateTime)
   {
      this.executionDateTime = executionDateTime;
   }

   public vistacore.order.Visit getVisit()
   {
      return this.visit;
   }

   public void setVisit(vistacore.order.Visit visit)
   {
      this.visit = visit;
   }

   public Sign(java.lang.String comment,
         java.lang.String executionUserSignatureCode,
         java.lang.String executionUserId,
         java.lang.String executionUserName,
         java.lang.String executionDateTime, vistacore.order.Visit visit)
   {
      this.comment = comment;
      this.executionUserSignatureCode = executionUserSignatureCode;
      this.executionUserId = executionUserId;
      this.executionUserName = executionUserName;
      this.executionDateTime = executionDateTime;
      this.visit = visit;
   }

}