package vistacore.order.consult;

import vistacore.order.Provider;
import vistacore.order.Facility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SignalBody implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String reason;
   private java.lang.String comment;
   private Provider provider;
   private java.lang.String noteClinicalObjectUid;
   private java.lang.String scheduledDate;
   private Facility clinic;
   private java.lang.String status;

   private java.lang.String userId;

   private vistacore.order.Visit visit;

   private java.lang.String actionText;

   private String actionId;

   private java.lang.String executionUserId;

   private java.lang.String executionUserName;

   private String urgency;

   private java.lang.String earliestDate;

   private java.lang.String latestDate;

   private java.lang.String request;

   private java.lang.String cdsIntentResult;

   private java.lang.String noteTitle;

   private java.lang.String communityCareType;

   private java.lang.String communityCareStatus;

   private java.lang.String overrideReason;

   private java.lang.String orderable;

   private vistacore.order.Provider accptingProvider;

   private vistacore.order.Facility facility;

   private java.util.List<vistacore.order.consult.Condition> conditions;

   private vistacore.order.Provider acceptingProvider;

   private java.util.List<vistacore.order.consult.ConsultPreReqQuestion> questions;

   private java.util.List<vistacore.order.consult.ConsultPreReqOrder> ordersResults;
   
   private java.lang.String orderResultComment;

   public SignalBody()
   {
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public java.lang.String getScheduledDate()
   {
      return this.scheduledDate;
   }

   public void setScheduledDate(java.lang.String scheduledDate)
   {
      this.scheduledDate = scheduledDate;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.String userId)
   {
      this.userId = userId;
   }

   public java.lang.String getNoteClinicalObjectUid()
   {
      return this.noteClinicalObjectUid;
   }

   public void setNoteClinicalObjectUid(java.lang.String noteClinicalObjectUid)
   {
      this.noteClinicalObjectUid = noteClinicalObjectUid;
   }

   public vistacore.order.Visit getVisit()
   {
      return this.visit;
   }

   public void setVisit(vistacore.order.Visit visit)
   {
      this.visit = visit;
   }

   public java.lang.String getActionText()
   {
      return this.actionText;
   }

   public void setActionText(java.lang.String actionText)
   {
      this.actionText = actionText;
   }

   public java.lang.String getExecutionUserId()
   {
      return this.executionUserId;
   }

   public void setExecutionUserId(java.lang.String executionUserId)
   {
      this.executionUserId = executionUserId;
   }

   public java.lang.String getExecutionUserName()
   {
      return this.executionUserName;
   }

   public void setExecutionUserName(java.lang.String executionUserName)
   {
      this.executionUserName = executionUserName;
   }

   public vistacore.order.Provider getProvider()
   {
      return this.provider;
   }

   public void setProvider(vistacore.order.Provider provider)
   {
      this.provider = provider;
   }

   public vistacore.order.Facility getClinic()
   {
      return this.clinic;
   }

   public void setClinic(vistacore.order.Facility clinic)
   {
      this.clinic = clinic;
   }

   public java.lang.String getEarliestDate()
   {
      return this.earliestDate;
   }

   public void setEarliestDate(java.lang.String earliestDate)
   {
      this.earliestDate = earliestDate;
   }

   public java.lang.String getRequest()
   {
      return this.request;
   }

   public void setRequest(java.lang.String request)
   {
      this.request = request;
   }

   public java.lang.String getCdsIntentResult()
   {
      return this.cdsIntentResult;
   }

   public void setCdsIntentResult(java.lang.String cdsIntentResult)
   {
      this.cdsIntentResult = cdsIntentResult;
   }

   public java.lang.String getNoteTitle()
   {
      return this.noteTitle;
   }

   public void setNoteTitle(java.lang.String noteTitle)
   {
      this.noteTitle = noteTitle;
   }

   public java.lang.String getCommunityCareType()
   {
      return this.communityCareType;
   }

   public void setCommunityCareType(java.lang.String communityCareType)
   {
      this.communityCareType = communityCareType;
   }

   public java.lang.String getCommunityCareStatus()
   {
      return this.communityCareStatus;
   }

   public void setCommunityCareStatus(java.lang.String communityCareStatus)
   {
      this.communityCareStatus = communityCareStatus;
   }

   public java.lang.String getActionId()
   {
      return this.actionId;
   }

   public void setActionId(java.lang.String actionId)
   {
      this.actionId = actionId;
   }

   public java.lang.String getOverrideReason()
   {
      return this.overrideReason;
   }

   public void setOverrideReason(java.lang.String overrideReason)
   {
      this.overrideReason = overrideReason;
   }

   public java.lang.String getOrderable()
   {
      return this.orderable;
   }

   public void setOrderable(java.lang.String orderable)
   {
      this.orderable = orderable;
   }

   public vistacore.order.Provider getAccptingProvider()
   {
      return this.accptingProvider;
   }

   public void setAccptingProvider(vistacore.order.Provider accptingProvider)
   {
      this.accptingProvider = accptingProvider;
   }

   public vistacore.order.Facility getFacility()
   {
      return this.facility;
   }

   public void setFacility(vistacore.order.Facility facility)
   {
      this.facility = facility;
   }

   public java.util.List<vistacore.order.consult.Condition> getConditions()
   {
      return this.conditions;
   }

   public void setConditions(
         java.util.List<vistacore.order.consult.Condition> conditions)
   {
      this.conditions = conditions;
   }

   public java.lang.String getUrgency()
   {
      return this.urgency;
   }

   public void setUrgency(java.lang.String urgency)
   {
      this.urgency = urgency;
   }

   public java.lang.String getLatestDate()
   {
      return this.latestDate;
   }

   public void setLatestDate(java.lang.String latestDate)
   {
      this.latestDate = latestDate;
   }

   public vistacore.order.Provider getAcceptingProvider()
   {
      return this.acceptingProvider;
   }

   public void setAcceptingProvider(vistacore.order.Provider acceptingProvider)
   {
      this.acceptingProvider = acceptingProvider;
   }

   public java.util.List<vistacore.order.consult.ConsultPreReqQuestion> getQuestions()
   {
      return this.questions;
   }

   public void setQuestions(
         java.util.List<vistacore.order.consult.ConsultPreReqQuestion> questions)
   {
      this.questions = questions;
   }

   public java.util.List<vistacore.order.consult.ConsultPreReqOrder> getOrdersResults()
   {
      return this.ordersResults;
   }

   public void setOrdersResults(
         java.util.List<vistacore.order.consult.ConsultPreReqOrder> ordersResults)
   {
      this.ordersResults = ordersResults;
   }

   public SignalBody(
         java.lang.String reason,
         java.lang.String comment,
         vistacore.order.Provider provider,
         java.lang.String noteClinicalObjectUid,
         java.lang.String scheduledDate,
         vistacore.order.Facility clinic,
         java.lang.String status,
         java.lang.String userId,
         vistacore.order.Visit visit,
         java.lang.String actionText,
         java.lang.String actionId,
         java.lang.String executionUserId,
         java.lang.String executionUserName,
         java.lang.String urgency,
         java.lang.String earliestDate,
         java.lang.String latestDate,
         java.lang.String request,
         java.lang.String cdsIntentResult,
         java.lang.String noteTitle,
         java.lang.String communityCareType,
         java.lang.String communityCareStatus,
         java.lang.String overrideReason,
         java.lang.String orderable,
         vistacore.order.Provider accptingProvider,
         vistacore.order.Facility facility,
         java.util.List<vistacore.order.consult.Condition> conditions,
         vistacore.order.Provider acceptingProvider,
         java.util.List<vistacore.order.consult.ConsultPreReqQuestion> questions,
         java.util.List<vistacore.order.consult.ConsultPreReqOrder> ordersResults)
   {
      this.reason = reason;
      this.comment = comment;
      this.provider = provider;
      this.noteClinicalObjectUid = noteClinicalObjectUid;
      this.scheduledDate = scheduledDate;
      this.clinic = clinic;
      this.status = status;
      this.userId = userId;
      this.visit = visit;
      this.actionText = actionText;
      this.actionId = actionId;
      this.executionUserId = executionUserId;
      this.executionUserName = executionUserName;
      this.urgency = urgency;
      this.earliestDate = earliestDate;
      this.latestDate = latestDate;
      this.request = request;
      this.cdsIntentResult = cdsIntentResult;
      this.noteTitle = noteTitle;
      this.communityCareType = communityCareType;
      this.communityCareStatus = communityCareStatus;
      this.overrideReason = overrideReason;
      this.orderable = orderable;
      this.accptingProvider = accptingProvider;
      this.facility = facility;
      this.conditions = conditions;
      this.acceptingProvider = acceptingProvider;
      this.questions = questions;
      this.ordersResults = ordersResults;
   }

public java.lang.String getOrderResultComment() {
	return orderResultComment;
}

public void setOrderResultComment(java.lang.String orderResultComment) {
	this.orderResultComment = orderResultComment;
}

}