package vistacore.order.consult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Version implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String module;
   private java.lang.String path;
   private java.lang.String time;

   public Version()
   {
   }

   public java.lang.String getModule()
   {
      return this.module;
   }

   public void setModule(java.lang.String module)
   {
      this.module = module;
   }

   public java.lang.String getPath()
   {
      return this.path;
   }

   public void setPath(java.lang.String path)
   {
      this.path = path;
   }

   public java.lang.String getTime()
   {
      return this.time;
   }

   public void setTime(java.lang.String time)
   {
      this.time = time;
   }

   public Version(java.lang.String module, java.lang.String path,
         java.lang.String time)
   {
      this.module = module;
      this.path = path;
      this.time = time;
   }

}