BEGIN

    FOR t IN (SELECT TABLE_NAME FROM dba_tables WHERE OWNER = 'COMMUNICATION')
    LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON COMMUNICATION.' || t.TABLE_NAME || ' TO COMMUNICATIONUSER';
    END LOOP;

    EXCEPTION
       WHEN OTHERS
          THEN
                 DBMS_OUTPUT.put_line (SQLERRM);
                 DBMS_OUTPUT.put_line ('   ');
                 RAISE;
END;
/