source 'http://rubygems.org'

gem 'rake'
gem 'rspec',	'=2.14.1'
gem 'cucumber', '=2.0.2'
gem 'selenium-webdriver',     '=2.41.0'
gem 'rubocop',    			  '=0.18.1'
gem 'httparty'
gem 'jsonpath'

gem 'fog',                    '=1.21.0'
gem 'macaddr',                '=1.6.7'
gem 'nokogiri',		      '=1.6.6.2'
gem 'strftime', '=1.0.0'
gem 'iso8601', '=0.8.7'
gem 'json-schema', '=2.6.2'

